### ISSUE TITLE
Broken proxy_host setting

### ISSUE THREAD

**Issue by BrandonG777** [DobyTang/LazyLibrarian#1096]
f748efc8ec7b3723db0f2aa026716fc7cbddf0bd
unRAID 6.3.5
bookstrap
GoodReads
Docker repo linuxserver/lazylibrarian

Lazylibrarian is starting up...
Traceback (most recent call last):
File "/app/lazylibrarian/LazyLibrarian.py", line 243, in <module>
main()
File "/app/lazylibrarian/LazyLibrarian.py", line 155, in main
lazylibrarian.initialize()
File "/app/lazylibrarian/lazylibrarian/__init__.py", line 597, in initialize
BOOKSTRAP_THEMELIST = build_bookstrap_themes()
File "/app/lazylibrarian/lazylibrarian/__init__.py", line 1093, in build_bookstrap_themes
result, success = fetchURL(URL, headers=None, retry=False)
File "/app/lazylibrarian/lazylibrarian/cache.py", line 40, in fetchURL
proxies = proxyList()
File "/app/lazylibrarian/lazylibrarian/common.py", line 50, in proxyList
for item in getList(lazylibrarian.CONFIG['PROXY_TYPE']):
NameError: global name 'getList' is not defined

This was working fine until recent. Removing proxy_host from my config gets me back up and running but I prefer queries to run through my proxy.

**Comment by philborman** [comment]
Missing an import when I added multiple proxy types. Should be fixed later today, sorry about that.
