### ISSUE TITLE
Database error: table users has no column named Read

### ISSUE THREAD

**Issue by Outcats** [DobyTang/LazyLibrarian#1143]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

2017-12-13 23:53:19 | ERROR | DB_UPGRADE | dbupgrade.py | dbupgrade | 362 | Unhandled exception in database upgrade: Traceback (most recent call last):  File "S:\Websites\LazyLibrarian\lazylibrarian\dbupgrade.py", line 164, in dbupgrade    hashlib.md5('admin').hexdigest(), '', 65535, '', ''))  File "S:\Websites\LazyLibrarian\lazylibrarian\database.py", line 48, in action    sqlResult = self.connection.execute(query, args) OperationalError: table users has no column named Read
-- | -- | -- | -- | -- | -- | --
2017-12-13 23:53:19 | ERROR | DB_UPGRADE | database.py | action | 63 | Failed query: [INSERT into users (UserID, UserName, Name, Password, Email, Perms, Read) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
2017-12-13 23:53:19 | ERROR | DB_UPGRADE | database.py | action | 62 | Database error: table users has no column named Read
2017-12-13 23:53:19 | DEBUG | DB_UPGRADE | dbupgrade.py | dbupgrade | 110 | Database integrity check: ok
2017-12-13 23:53:18 | INFO | MAIN | webStart.py | initialize | 58 | Starting LazyLibrarian web server on http://0.0.0.0:5299/
2017-12-13 23:53:18 | INFO | MAIN | LazyLibrarian.py | main | 196 | Starting LazyLibrarian on port: 5299, webroot "/lazylibrarian"

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report. 
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1557519/debug.zip)

**Comment by Outcats** [comment]
Hope that is everything you need let me know if you need anything else?

**Comment by philborman** [comment]
Perfect thanks.  It was a silly typo, fixed now. Upgrade and reboot should get you up and running again.

**Comment by Outcats** [comment]
Hey thanks man, did the update and restarted it and can't see the error any more.
