### ISSUE TITLE
Can't start after latest update

### ISSUE THREAD

**Issue by moiecoute** [DobyTang/LazyLibrarian#1191]
Hi,

I did an update this morning. After the update LazyLibrarian will not start. It returns the following.

_[moiecoute@AmigaOS LazyLibrarian]$ python2 LazyLibrarian.py
Traceback (most recent call last):
  File "LazyLibrarian.py", line 14, in <module>
    import lazylibrarian
  File "/home/moiecoute/LazyLibrarian/lazylibrarian/__init__.py", line 33, in <module>
    from lazylibrarian import logger, postprocess, searchbook, searchrss, librarysync, versioncheck, database, \
  File "/home/moiecoute/LazyLibrarian/lazylibrarian/postprocess.py", line 27, in <module>
    from lazylibrarian import database, logger, utorrent, transmission, qbittorrent, \
  File "/home/moiecoute/LazyLibrarian/lazylibrarian/utorrent.py", line 25, in <module>
    from lazylibrarian.common import USER_AGENT
  File "/home/moiecoute/LazyLibrarian/lazylibrarian/common.py", line 33, in <module>
    import lib.requests as requests
  File "/home/moiecoute/LazyLibrarian/lib/requests/__init__.py", line 43, in <module>
    import urllib3
ImportError: No module named urllib3_

Any thoughts?

Thanks
J

**Comment by philborman** [comment]
Yes, I've broken it!
I upgraded the requests library because of an issue with talking to goodreads. Turned out the problem was not requests, but a docker issue so it didn't need upgrading anyway.
I have reverted back to the older version now. Sorry about that.

**Comment by moiecoute** [comment]
No worries. Thanks. I will download the latest update.
