### ISSUE TITLE
Filtering books in the author screen

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#1238]
I'm recently running into an AJAX error when filtering book titles in the author page. 

The console shows that getBooks is returning a 500 error, and here's the Traceback:
`
Traceback (most recent call last):
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/webServe.py", line 1465, in getBooks
    if sSearch.lower() in _dict.get(key, '').lower():
AttributeError: 'NoneType' object has no attribute 'lower'
`

**Comment by philborman** [comment]
Interesting. Looks like one of the text fields in the books table is returning None instead of an empty string. Shouldn't really happen. Easy enough to trap it, but probably means there is some database corruption. You could add a debug line to webServe.py to track it down if you want, 
Add  just above 1465, 
 if _dict.get(key, '') is None:
    print(_dict)
