### ISSUE TITLE
Search error:  "TypeError: list indices must be integers, not str"

### ISSUE THREAD

**Issue by seanvree** [DobyTang/LazyLibrarian#1353]
**Environment**:

### Source of your LazyLibrarian installation: GIT

**ISSUE**:

Can't search for author or any other method:

```
Unhandled exception in GB.find_results: Traceback (most recent call last): File "c:\lazylibrarian\lazylibrarian\gb.py", line 198, in find_results AuthorID = match['authorid'] TypeError: list indices must be integers, not str
```

**LOGS**:

```
24-Apr-2018 19:11:45 - DEBUG   :: SAVELOG : common.py:saveLog:798 : Found "Debug log ON" line 4 in C:\LazyLibrarian\Logs\lazylibrarian.log
24-Apr-2018 19:11:45 - DEBUG   :: SAVELOG : common.py:saveLog:830 : Redacted 39 passwords/apikeys
24-Apr-2018 19:11:45 - DEBUG   :: SAVELOG : common.py:saveLog:831 : 915 log lines written to C:\LazyLibrarian\Logs\debug.log
24-Apr-2018 19:11:45 - INFO    :: SAVELOG : webServe.py:saveLog:3249 : Debug log saved as C:\LazyLibrarian\Logs\debug.zip
24-Apr-2018 19:13:12 - DEBUG   :: GB-RESULTS : gb.py:find_results:79 : Now searching Google Books API with searchterm: George Orwell
24-Apr-2018 19:13:12 - DEBUG   :: GB-RESULTS : gb.py:find_results:124 : Searching url: https://www.googleapis.com/books/v1/volumes?q=inauthor%3A%22George+Orwell%22&startIndex=0&printType=books&key=<redacted>&maxResults=40
24-Apr-2018 19:13:12 - ERROR   :: GB-RESULTS : gb.py:find_results:241 : Unhandled exception in GB.find_results: Traceback (most recent call last):
  File "c:\lazylibrarian\lazylibrarian\gb.py", line 198, in find_results
    AuthorID = match['authorid']
TypeError: list indices must be integers, not str
24-Apr-2018 19:14:15 - DEBUG   :: SAVELOG : common.py:saveLog:780 : Processing logfile [C:\LazyLibrarian\Logs\lazylibrarian.log]
```

**Comment by seanvree** [comment]
@philborman   This error is back with version: 9f3943a14d9e51a08ba17db0ef7ef0494d820696 


```
Unhandled exception in GB.find_results: Traceback (most recent call last): File "c:\lazylibrarian\lazylibrarian\gb.py", line 144, in find_results book = bookdict(item) File "c:\lazylibrarian\lazylibrarian\gb.py", line 786, in bookdict series, seriesNum = item.split('(')[1].split(' Series ') ValueError: need more than 1 value to unpack
```

**Comment by philborman** [comment]
Thanks, it's a different error though. ValueError rather than TypeError.
It looks like googlebooks is giving us series name info in a format we can't handle.
I have just added a bit of code to trap the error, but it would be good to know what the series information was so we can read it. We currently handle formats like (Discworld 24) (Discworld #24) (discworld Series 24)  Book 24 of Discworld  

Anything useful in the logs?

**Comment by seanvree** [comment]
@philborman  No, that's the only error I'm getting. Debug is on.
