### ISSUE TITLE
Remove mags deleted them instead...

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1358]
Remove mags deleted them instead...

I removed about 30 magazine, and re-scanned but they couldn't be found.
They were deleted...

**Comment by MrMxyzptlk** [comment]
I just noticed that they are actually in the Windows directory, they just aren't being scanned into LL after removal?

**Comment by philborman** [comment]
Remove just deletes the database entry, doesn't touch the files, so as long as the are still in the same folder a libraryscan should pick them up again. Try with debug log enabled and you should see what's going on.

**Comment by MrMxyzptlk** [comment]
Tons of errors in logs after scan....


2018-04-25 15:44:48 | ERROR | Unhandled exception in magazineScan: Traceback (most recent call last): File "X:\Applications\lazylibrarian\lazylibrarian\magazinescan.py", line 156, in magazineScan regex_pass, issuedate, year = lazylibrarian.searchmag.get_issue_date(exploded) File "X:\Applications\lazylibrarian\lazylibrarian\searchmag.py", line 522, in get_issue_date month = month2num(nzbtitle_exploded[pos - 2]) IndexError: list index out of range
-- | -- | --
2018-04-25 15:44:48 | WARNING | Invalid name format for [Blint International - 66.pdf]
2018-04-25 15:44:48 | WARNING | Invalid name format for [Bienestar - 12-09.pdf]
2018-04-25 15:44:47 | WARNING | Invalid name format for [Bare Journal - 01.pdf]
2018-04-25 15:44:47 | WARNING | Invalid name format for [BackPocket - #5.pdf]
2018-04-25 15:44:47 | WARNING | Invalid name format for [BackPocket - #32.pdf]
2018-04-25 15:44:47 | WARNING | Invalid name format for [BackPocket - #3.pdf]
2018-04-25 15:44:47 | WARNING | Invalid name format for [BackPocket - #26.pdf]
2018-04-25 15:44:47 | WARNING | Invalid name format for [BackPocket - #19.pdf]
2018-04-25 15:44:47 | WARNING | Invalid name format for [BackPocket - #10.pdf]
2018-04-25 15:44:47 | WARNING | Invalid name format for [Area 51 - 00.pdf]
2018-04-25 15:44:47 | WARNING | Invalid name format for [ANP Quarterly - 2-5.pdf]
2018-04-25 15:44:44 | WARNING | Invalid name format for [A - 2017-09-90.pdf]
2018-04-25 15:44:44 | INFO | Checking [X:\Anthony\Magazine\Magazines\] for magazines

**Comment by philborman** [comment]
The index error needs fixing, but the magazines with incorrect names are definitely incorrect :-)
2017-09-90 is not a valid date, nor is 12-09, and the issue numbers need to be at least 3 digits with leading zeros to be recognised, so [BackPocket - #19.pdf]  would need to be [BackPocket - #019.pdf] in order to be recognised.  Not sure how the "wrong" dates got accepted first time round...

**Comment by MrMxyzptlk** [comment]
I changed the date format after you updated LL to allow it.

I changed the format from year-day-month to month-day-year in the config section.

**Comment by MrMxyzptlk** [comment]
$m-$d-$Y

**Comment by philborman** [comment]
Sure, but none of those dates are anything we can recognise as a valid date. If we can recognise a date in the filename (or the download name) we should create a database entry using yyyy-mm-dd or an issue number and then display it differently in the tables depending on config settings. The config settings only affect how dates are displayed, we always store in the database as yyyy-mm-dd or a 4 digit  zero padded number for sorting purposes.  Actually just realised my earlier answer was incomplete. If it's a magazine with an issue number we accept Issue/No/Nr/Vol n as valid too, so` [BackPocket - Vol 19.pdf]`  would be ok. We just need some way to know the 19 is an issue number

**Comment by MrMxyzptlk** [comment]
Yeah, like I said, LL found, downloaded, and imported all of those previously. So now what? How do I get all 1000+ mags back in LL?

**Comment by philborman** [comment]
We can accept # as another issue number identifier like Issue/No/Nr/Vol which will pick up most of them, just not the ones where there is an invalid date, how can we tell what magazine issue it is?
Not sure how #10 would have been accepted before, but 0005 should be fine. 
[Bienestar - 12-09.pdf]  could be either September 2012 or December 2009, we can't tell, and  [A - 2017-09-90.pdf], well September must have seemed endless that year..

Pushing the '#' change shortly

**Comment by MrMxyzptlk** [comment]
OK, I was able to get all of the mags back with a few minor renaming chores.

I do have some magazines that are seasonal (Spring, Summer, Fall, Winter), that is how they label the issues. I have some that are annual (2016). Some that show #1, or #01. Some that show volume 2 issue 09 or 9. 

We need some way to be able to set a magazine as a particular format?

Manually choosing this option, is not an issue...

**Comment by philborman** [comment]
The seasonal ones should be ok, we allow Spring, Summer, Autumn/Fall, Winter as valid months, but only with English month names. Must also contain a valid year though. "Magazine title Spring 2018" or "Magazine title 2018 Spring issue" or similar should be ok.

`#1` and `#01` should work now, added that last night.

 Annual is more of a problem as if we just look for a year in the name we end up matching all sorts of "special edition" issues, though it could be used as an if-all-else-fails

volume 2 issue 9 and similar are also hard to handle, but not impossible, I will see about that.

The main problem with matching dates is that the people that upload the mags are free to name them however they want, and the mags themselves don't include any metadata that lets us check, unlike books.

**Comment by MrMxyzptlk** [comment]
Thanks for all the effort!

**Comment by philborman** [comment]
It's a challenge, keeps me from getting too bored now I'm retired!
Latest version now handles volume x issue y with or without a year, and I added annual too, if it causes any problems it might need to be removed again, or made switchable, need to think about it and see how best to do it. 
There is also an api call you can use to see what we think the issue number is for a filename so you can try out unusual patterns before importing them if you want. getIssueName&name=some+magazine+march+2017.pdf
Shows the value we would store in the database 2017-03-01
