### ISSUE TITLE
Error while trying to update

### ISSUE THREAD

**Issue by nncrypted** [DobyTang/LazyLibrarian#137]
I get the following in terminal when I try to update to current version.
Traceback (most recent call last):
  File "LazyLibrarian.py", line 160, in <module>
    main()
  File "LazyLibrarian.py", line 155, in main
    lazylibrarian.shutdown(restart=True, update=True)
  File "/opt/LazyLibrarian/lazylibrarian/__init__.py", line 820, in shutdown
    config_write()
  File "/opt/LazyLibrarian/lazylibrarian/__init__.py", line 678, in config_write
    new_config['Pushover']['pushover_priority'] = int(PUSHOVER_PRIORITY)
ValueError: invalid literal for int() with base 10: ''

**Comment by nncrypted** [comment]
Fixed
