### ISSUE TITLE
LL not Importing Torrents through qBittorrent

### ISSUE THREAD

**Issue by rgupta9400** [DobyTang/LazyLibrarian#1448]
### LazyLibrarian version number (at the bottom of config page)
c7de4d744427cd1640fb9c64cd8f160c00209195 
### Operating system used (windows, mac, linux, NAS type)
Windows
### Interface in use (default, bookstrap)
bookstrap
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Zip File
### Relevant debug log with api keys and any passwords redacted
2018-06-03 18:34:06 | ERROR | SEARCHBOOK | resultlist.py | downloadResult | 279 | Unhandled exception in downloadResult: Traceback (most recent call last): File "C:\LazyLibrarian\lazylibrarian\resultlist.py", line 257, in downloadResult controlValueDict["NZBurl"], newValueDict["AuxInfo"]) File "C:\LazyLibrarian\lazylibrarian\downloadmethods.py", line 328, in TORDownloadMethod tor_title = qbittorrent.getName(hashid) File "C:\LazyLibrarian\lazylibrarian\qbittorrent.py", line 301, in getName torrents = qbclient._get_list() File "C:\LazyLibrarian\lazylibrarian\qbittorrent.py", line 143, in _get_list return self._command('query/torrents', args) File "C:\LazyLibrarian\lazylibrarian\qbittorrent.py", line 123, in _command return response.json() AttributeError: addinfourl instance has no attribute 'json'
-- | -- | -- | -- | -- | -- | --
2018-06-03 18:34:05 | INFO | POSTPROCESS | postprocess.py | processDir | 829 | 0 books/mags processed.
2018-06-03 18:34:05 | INFO | SEARCHBOOK | searchbook.py | search_book | 298 | Requesting eBook download: 99% http://localhost:9117/jackett/api/v2.0/indexers/1337x/results/torznab: Prince Caspian C S Lewis viny
2018-06-03 18:34:05 | INFO | SEARCHBOOK | searchbook.py | search_book | 292 | Found NZB result: book 99%, http://localhost:9117/jackett/api/v2.0/indexers/1337x/results/torznab priority 2
2018-06-03 18:34:05 | INFO | SEARCHBOOK | resultlist.py | findBestResult | 208 | Best match (99%): Prince Caspian C S Lewis viny using book search, http://localhost:9117/jackett/api/v2.0/indexers/1337x/results/torznab priority

I am running LL with Usenet and Torrents (qBittorrent) both. Torrent indexing works through Torznab (Jackett). Usenet works smoothly, but torrents are causing a problem. LL snatches the torrents, but I think it is not able to rename the torrent like it does with nzbds. Then, when post-processing runs, I think it skips it because it is not finding an expected file name. 

The torrents themselves download fine into the same directory as the Usenet client, just without the naming convention. qBittorrent itself is on a VM, and I use a shared drive. I don't seem to have any issues with Radarr or Sonarr using qBittorrent, but I was able to remote map the directory in those services -- not sure if that is causing issues.

Not sure if it matters, but I use calibredb. I think the Post-Processor is not even getting that far though.

Apologies if I missed something, I am very new to this.

**Comment by philborman** [comment]
Sorry, I broke that a few days ago and didn't notice. Will push a fix in a few hours.
Only affects qbittorrent when asking it for the torrent name, we fall over trying to get the reply.

**Comment by rgupta9400** [comment]
It seems to be working now. 

Thanks!
