### ISSUE TITLE
Vacuum database via API returns "Warning: You can only execute one statement at a time."

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1464]
/usr/bin/curl -q "http://localhost:5299/api?apikey=APIKEY&cmd=vacuum"

I always get the below error, even if I stop and restart LL and immediately run curl.  I have it set to vacuum once a day in crontab, which is probably excessive.

<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/Users/kids/src/LazyLibrarian-master/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/Users/kids/src/LazyLibrarian-master/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Users/kids/src/LazyLibrarian-master/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Users/kids/src/LazyLibrarian-master/lazylibrarian/webServe.py", line 4225, in api
    return a.fetchData
  File "/Users/kids/src/LazyLibrarian-master/lazylibrarian/api.py", line 223, in fetchData
    methodToCall(**self.kwargs)
  File "/Users/kids/src/LazyLibrarian-master/lazylibrarian/api.py", line 424, in _vacuum
    self.data = self._dic_from_query("vacuum; pragma integrity_check")
  File "/Users/kids/src/LazyLibrarian-master/lazylibrarian/api.py", line 242, in _dic_from_query
    rows = myDB.select(query)
  File "/Users/kids/src/LazyLibrarian-master/lazylibrarian/database.py", line 104, in select
    sqlResults = self.action(query, args).fetchall()
  File "/Users/kids/src/LazyLibrarian-master/lazylibrarian/database.py", line 46, in action
    sqlResult = self.connection.execute(query)
Warning: You can only execute one statement at a time.
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 3.6.0</a>
      </span>
    </div>
    </body>
</html>

**Comment by philborman** [comment]
Fixed in latest issue. you can to both in one command in sql, but not via the api unfortunately.
Vacuuming once every few days or even weeks is probably enough. Check the database file sizes before and after to see what difference it made. We do an automatic vacuum after a database upgrade, but that can be months in between. Probably fairly harmless.

**Comment by dkids** [comment]
Tried it and it seemed to work fine.   Fixed.  Thank you.
