### ISSUE TITLE
unable to launch - "undefined symbol: magic_open"

### ISSUE THREAD

**Issue by OneCDOnly** [DobyTang/LazyLibrarian#1487]
This was cloned from source only a few minutes ago. 

I'm trying to run this on a QNAP NAS (running a heavily-modified version of Ubuntu as an embedded OS), but I'm getting this error: 
```
# /opt/bin/python2.7 /share/MD0_DATA/.qpkg/LazyLibrarian/LazyLibrarian/LazyLibrarian.py -d --pidfile /tmp/LazyLibrarian.pid
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/LazyLibrarian/LazyLibrarian/LazyLibrarian.py", line 13, in <module>
    import lazylibrarian
  File "/share/MD0_DATA/.qpkg/LazyLibrarian/LazyLibrarian/lazylibrarian/__init__.py", line 29, in <module>
    from lazylibrarian import logger, postprocess, searchbook, searchrss, librarysync, versioncheck, database, \
  File "/share/MD0_DATA/.qpkg/LazyLibrarian/LazyLibrarian/lazylibrarian/searchbook.py", line 22, in <module>
    from lazylibrarian.resultlist import findBestResult, downloadResult
  File "/share/MD0_DATA/.qpkg/LazyLibrarian/LazyLibrarian/lazylibrarian/resultlist.py", line 22, in <module>
    from lazylibrarian.downloadmethods import NZBDownloadMethod, TORDownloadMethod, DirectDownloadMethod
  File "/share/MD0_DATA/.qpkg/LazyLibrarian/LazyLibrarian/lazylibrarian/downloadmethods.py", line 29, in <module>
    import lib.magic as magic
  File "/share/MD0_DATA/.qpkg/LazyLibrarian/LazyLibrarian/lib/magic/__init__.py", line 361, in <module>
    add_compat(globals())
  File "/share/MD0_DATA/.qpkg/LazyLibrarian/LazyLibrarian/lib/magic/__init__.py", line 325, in add_compat
    from . import compat
  File "/share/MD0_DATA/.qpkg/LazyLibrarian/LazyLibrarian/lib/magic/compat.py", line 61, in <module>
    _open = _libraries['magic'].magic_open
  File "/opt/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
  File "/opt/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
AttributeError: /opt/bin/python2.7: undefined symbol: magic_open
```
```
# pip list
Package      Version
------------ -------
asn1crypto   0.23.0 
attrs        17.4.0 
cffi         1.11.4 
Cheetah      2.4.4  
cryptography 2.1.4  
enum34       1.1.6  
idna         2.6    
ipaddress    1.0.19 
libmagic     1.0    
Markdown     2.6.11 
pip          10.0.1 
ply          3.10   
pycparser    2.18   
pyOpenSSL    17.5.0 
sabyenc      3.3.5  
setuptools   39.2.0 
six          1.11.0 
```
```
# opkg list-installed
alsa-lib - 1.1.5-1
ar - 2.27-1
binutils - 2.27-1
ca-certificates - 20180409
chattr - 1.44.1-1
coreutils - 8.23-3
coreutils-nice - 8.23-3
e2fsprogs - 1.44.1-1
entware-opt - 227000-3
entware-release - 1.0-2
entware-upgrade - 1.0-1
ffprobe - 3.2.10-3
file - 5.25-2
findutils - 4.6.0-1
gcc - 6.3.0-1b
git - 2.16.3-1
git-http - 2.16.3-1
grep - 2.26-1
ionice - 2.32-2
lame-lib - 3.100-1
less - 487-1
libbfd - 2.27-1
libblkid - 2.32-2
libbz2 - 1.0.6-3
libc - 2.27-8
libcomerr - 1.44.1-1
libcurl - 7.59.0-2
libdb47 - 4.7.25.4.NC-5
libexpat - 2.2.5-1
libext2fs - 1.44.1-1
libffi - 3.2.1-3
libffmpeg-full - 3.2.10-3
libgcc - 7.3.0-8
libgdbm - 1.11-1
libiconv-full - 1.11.1-3
libintl-full - 0.19.8.1-1
libmagic - 5.25-2
libncurses - 6.1-1
libncursesw - 6.1-1
libopcodes - 2.27-1
libopenssl - 1.0.2o-1
libopus - 1.2.1-1
libpcre - 8.41-2
libpthread - 2.27-8
librt - 2.27-8
libsqlite3 - 3230100-1
libss - 1.44.1-1
libssp - 7.3.0-8
libstdcpp - 7.3.0-8
libuuid - 2.32-2
libx264 - snapshot-20170623-2245-stable-1
libxml2 - 2.9.8-1
locales - 2.27-8
lsattr - 1.44.1-1
nano - 2.9.6-1
objdump - 2.27-1
opkg - 2011-04-08-9c97d5ec-17b
p7zip - 16.02-1
python - 2.7.15-1
python-asn1crypto - 0.23.0-1
python-attrs - 17.4.0-2
python-base - 2.7.15-1
python-cffi - 1.11.4-1
python-codecs - 2.7.15-1
python-compiler - 2.7.15-1
python-cryptography - 2.1.4-2
python-ctypes - 2.7.15-1
python-db - 2.7.15-1
python-decimal - 2.7.15-1
python-dev - 2.7.15-1
python-distutils - 2.7.15-1
python-email - 2.7.15-1
python-enum34 - 1.1.6-3
python-gdbm - 2.7.15-1
python-idna - 2.6-2
python-ipaddress - 1.0.19-2
python-lib2to3 - 2.7.15-1
python-light - 2.7.15-1
python-logging - 2.7.15-1
python-multiprocessing - 2.7.15-1
python-ncurses - 2.7.15-1
python-openssl - 2.7.15-1
python-pip - 9.0.3-1
python-pip-conf - 0.1-1
python-ply - 3.10-2
python-pycparser - 2.18-2
python-pydoc - 2.7.15-1
python-pyopenssl - 17.5.0-2
python-setuptools - 39.0.1-1
python-six - 1.11.0-2
python-sqlite3 - 2.7.15-1
python-unittest - 2.7.15-1
python-xml - 2.7.15-1
terminfo - 6.1-1
unrar - 5.6.1-1
zlib - 1.2.11-2
zoneinfo-asia - 2018e-1
zoneinfo-europe - 2018e-1
```

Can anyone please advise what I'm doing wrong? 

Thank you.

**Comment by philborman** [comment]
We are getting an unexpected error trying to load the "magic" library. It's an optional library, but the code to say "ok, skip that" isn't working.  You can get around it by installing python-magic  ( pip install python-magic )
It's useful to have the magic library if you use libgen as a source, but the error needs trapping anyway. Will push a fix for it tomorrow. Thanks for the bug report, let me know if the pip install solves it.

**Comment by OneCDOnly** [comment]
```
# pip install python-magic
Collecting python-magic
  Downloading https://files.pythonhosted.org/packages/42/a1/76d30c79992e3750dac6790ce16f056f870d368ba142f83f75f694d93001/python_magic-0.4.15-py2.py3-none-any.whl
Installing collected packages: python-magic
Successfully installed python-magic-0.4.15
# /opt/bin/python2.7 /share/MD0_DATA/.qpkg/LazyLibrarian/LazyLibrarian/LazyLibrarian.py -d --pidfile /tmp/LazyLibrarian.pid
Lazylibrarian is starting up...
30-Jun-2018 05:57:21 - INFO :: MAIN : __init__.py:initialize:608 : Log level set to [1]- Log Directory is [/share/MD0_DATA/.qpkg/LazyLibrarian/LazyLibrarian/Logs] - Config level is [1]
30-Jun-2018 05:57:21 - INFO :: MAIN : __init__.py:initialize:614 : Screen Log set to INFO
30-Jun-2018 05:57:21 - INFO :: MAIN : __init__.py:config_read:897 : Config file loaded
30-Jun-2018 05:57:21 - INFO :: MAIN : __init__.py:initialize:658 : Database is version 0, integrity check: ok
30-Jun-2018 05:57:31 - INFO :: MAIN : __init__.py:build_bookstrap_themes:1278 : Bookstrap found 16 themes
```
Much better. Thank you @philborman.

Should we leave this issue open until the fix has been commited?

**Comment by philborman** [comment]
Yes I will close it tomorrow, thanks

**Comment by OneCDOnly** [comment]
Hi, I've just tried the new version, but got the same error as before:
`AttributeError: /opt/bin/python2.7: undefined symbol: magic_open`

However, the suggested workaround gets things working again.

Can this issue be reopened please?

**Comment by philborman** [comment]
I will have another look, is there a traceback for the error like last time in case it's a different place?

**Comment by OneCDOnly** [comment]
Sorry, @philborman, I've just updated my comment.

**Comment by OneCDOnly** [comment]
... and after that last merge, it now works fine. 

Thank you @philborman.
