### ISSUE TITLE
Traceback in pp

### ISSUE THREAD

**Issue by barbequesauce** [DobyTang/LazyLibrarian#1494]
LL commit 6917a0c455f331c3ea3f985337a282152de1a3f2 on Raspbian Jessie using bookstrap & Goodreads, installed from git.

Troubleshooting a bunch of snatched entries sitting at 100% for days and found a traceback... Log snippet below, can provide full debug zip if needed.

```
06-Jul-2018 10:36:03 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:491 : Found folder (100%) [/mnt/skytopcliff/completed/books/Madeline Ashby Zombies Condoms and Shenzhen The Surprising Link Between the Undead and The Unborn zip] for eBook Madeline Ashby Zombies Condoms and Shenzhen The Surprising Link Between the Undead and The Unborn zip                                    
06-Jul-2018 10:36:03 - DEBUG   :: POSTPROCESS : postprocess.py:unpack_archive:254 : Skipping zipped file Madeline Ashby - Zombies, Condoms and Shenzhen/                                        
06-Jul-2018 10:36:03 - DEBUG   :: POSTPROCESS : postprocess.py:unpack_archive:254 : Skipping zipped file Madeline Ashby - Zombies, Condoms and Shenzhen/ashbyZombies, Condoms and Shenzhen-Dateien/                                                                                             
06-Jul-2018 10:36:03 - ERROR   :: POSTPROCESS : postprocess.py:processDir:816 : Unhandled exception in processDir: Traceback (most recent call last):                                           
  File "/opt/LazyLibrarian/lazylibrarian/postprocess.py", line 497, in processDir               
    res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle)                         
  File "/opt/LazyLibrarian/lazylibrarian/postprocess.py", line 250, in unpack_archive           
    with open(os.path.join(targetdir, item), "wb") as f:                                        
IOError: [Errno 2] No such file or directory: u'/mnt/skytopcliff/completed/books/Madeline Ashby Zombies Condoms and Shenzhen The Surprising Link Between the Undead and The Unborn zip/Madeline Ashby Zombies Condoms and Shenzhen The Surprising Link Between the Undead and The Unborn zip.unpack/Madeline Ashby - Zombies, Condoms and Shenzhen/ashbyZombies, Condoms and Shenzhen-Dateien/102walkbowl.jpg'      
```

**Comment by philborman** [comment]
LL is trying to be clever and only unpack the files we want from the zip, but unfortunately we're not creating the subdirectories as they don't have an extension (epub, mobi etc). Should be easy to fix, but probably tomorrow now. Will change it so we unpack everything regardless.

**Comment by barbequesauce** [comment]
Thanks - your efforts are greatly appreciated!

**Comment by barbequesauce** [comment]
Looks good, thanks!
