### ISSUE TITLE
Cant Start after the update

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#150]
````
Traceback (most recent call last):
  File "/Users/maxcore/Downloads/LazyLibrarian-master/LazyLibrarian.py", line 4, in <module>
    import lazylibrarian
  File "/Users/maxcore/Downloads/LazyLibrarian-master/lazylibrarian/__init__.py", line 12, in <module>
    from lazylibrarian import logger, postprocess, searchnzb, searchtorrents, SimpleCache, librarysync
  File "/Users/maxcore/Downloads/LazyLibrarian-master/lazylibrarian/librarysync.py", line 6, in <module>
    from lazylibrarian import logger, database, importer
  File "/Users/maxcore/Downloads/LazyLibrarian-master/lazylibrarian/importer.py", line 5, in <module>
    from lazylibrarian.gr import GoodReads
  File "/Users/maxcore/Downloads/LazyLibrarian-master/lazylibrarian/gr.py", line 15, in <module>
    import unidecode
ImportError: No module named unidecode
````

**Comment by stumueller** [comment]
I managed to get it working by running
pip install unidecode
pip install lxml

**Comment by JaBaine** [comment]
I may be having the same issue but for the life of me I am unable to figure out how to implement what @stumueller is suggesting. I will add my log file below

**Comment by JaBaine** [comment]
This is directly after updating to the latest commit
```
18-Oct-2015 12:33:58 - INFO    :: MAIN : Log level set to [2]- Log Directory is [C:\Program Files (x86)\LazyLibrarian\Logs] - Config level is [2]
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : match_ratio -> 60
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : http_host -> 0.0.0.0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : http_user -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : http_pass -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : http_root -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : http_look -> default
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : launch_browser -> 1
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : proxy_host -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : proxy_type -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : logdir -> C:\Program Files (x86)\LazyLibrarian\Logs
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : imp_preflang -> en, eng, en-US, Unknown, en-GB, None
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : imp_autoadd -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : imp_onlyisbn -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : git_user -> dobytang
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : git_repo -> lazylibrarian
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : git_branch -> master
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : install_type -> source
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : current_version -> eef56e5d1e981f9899bc3b08bcb3c0ed55103800
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : latest_version -> eef56e5d1e981f9899bc3b08bcb3c0ed55103800
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : commits_behind -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : sab_host -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : sab_port -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : sab_subdir -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : sab_user -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : sab_pass -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : sab_api -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : sab_cat -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nzbget_host -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nzbget_user -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nzbget_pass -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nzbget_cat -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nzbget_priority -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : destination_copy -> 1
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : destination_dir -> D:\Media\Ebooks\calibre library\Fiction
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : download_dir -> D:\Media\Unsorted Media\ebooks\_Temp
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : use_nzb -> 1
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : use_tor -> 1
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nzb_downloader_sabnzbd -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nzb_downloader_nzbget -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nzb_downloader_blackhole -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nzb_blackholedir -> D:\Media\Unsorted Media\_Downloads\
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : usenet_retention -> None
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nzbmatrix -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nzbmatrix_user -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nzbmatrix_api -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : newznab -> 1
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : newznab_host -> http://api.nzb.su
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : newznab_api -> e17381e7562706e65f0ca3c8dfc893ac
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : newznab2 -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : newznab_host2 -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : newznab_api2 -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : tor_downloader_blackhole -> 1
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : tor_downloader_utorrent -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : tor_downloader_transmission -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : tor_downloader_deluge -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : numberofseeders -> 1
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : torrent_dir -> D:\Media\Unsorted Media\_Downloads\
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : utorrent_host -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : utorrent_user -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : utorrent_pass -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : utorrent_label -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : transmission_host -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : transmission_user -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : transmission_pass -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : deluge_host -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : deluge_port -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : deluge_user -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : deluge_pass -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : kat -> 1
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : usenetcrawler -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : usenetcrawler_host -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : usenetcrawler_api -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : newzbin -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : newzbin_uid -> None
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : newzbin_pass -> None
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : ebook_type -> epub, mobi, pdf
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : search_interval -> 360
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : scan_interval -> 10
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : versioncheck_interval -> 24
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : full_scan -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : notfound_status -> Skipped
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : add_author -> 1
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : ebook_dest_folder -> $Author/$Title
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : ebook_dest_file -> $Title - $Author
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : mag_dest_folder -> _Magazines/$Title/$IssueDate
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : mag_dest_file -> $IssueDate - $Title
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : use_twitter -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : twitter_notify_onsnatch -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : twitter_notify_ondownload -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : twitter_username -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : twitter_password -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : twitter_prefix -> LazyLibrarian
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : use_boxcar -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : boxcar_notify_onsnatch -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : boxcar_notify_ondownload -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : boxcar_token -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : use_pushbullet -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : pushbullet_notify_onsnatch -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : pushbullet_notify_ondownload -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : pushbullet_token -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : pushbullet_deviceid -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : use_pushover -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : pushover_onsnatch -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : pushover_ondownload -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : pushover_keys -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : pushover_apitoken -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : pushover_priority -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nma_enabled -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nma_apikey -> 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nma_priority -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : nma_onsnatch -> 0
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : book_api -> GoodReads
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : gr_api -> ckvsiSDsuqh7omh74ZZ6Q
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : gb_api -> 
18-Oct-2015 12:33:58 - INFO    :: MAIN : Checking database
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : (LazyLibrarian) Setup install,versions and commit status
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : (getInstallType) [Source]install detected. Setting Branch to [master]
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : (updateVersionFile) Updating [C:\Program Files (x86)\LazyLibrarian\version.txt] with value [eef56e5d1e981f9899bc3b08bcb3c0ed55103800]
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : (getCurrentVersion) - Install type [source] Local Version is set to [eef56e5d1e981f9899bc3b08bcb3c0ed55103800] 
18-Oct-2015 12:33:58 - DEBUG   :: MAIN : (getLatestVersionaFromGit) Retrieving latest version information from github command=[https://api.github.com/repos/dobytang/lazylibrarian/commits/master]
18-Oct-2015 12:34:00 - DEBUG   :: MAIN : (getLatestVersionaFromGit) Branch [master] has Latest Version has been set to [b3082ba7f0c0721e71b4d6b93a5a0ae875f78119]
18-Oct-2015 12:34:00 - INFO    :: MAIN : [VersionCheck] -  Comparing currently installed version with latest github version
18-Oct-2015 12:34:00 - DEBUG   :: MAIN : (getCommitDifferenceFromGit) -  Check for differences between local & repo by [https://api.github.com/repos/dobytang/LazyLibrarian/compare/eef56e5d1e981f9899bc3b08bcb3c0ed55103800...b3082ba7f0c0721e71b4d6b93a5a0ae875f78119]
18-Oct-2015 12:34:00 - DEBUG   :: MAIN : JSONDecode url
18-Oct-2015 12:34:00 - DEBUG   :: MAIN : pull total_commits from json object
18-Oct-2015 12:34:00 - DEBUG   :: MAIN : (getCommitDifferenceFromGit) -  GitHub reports as follows Status [ahead] - Ahead [9] - Behind [0] - Total Commits [9] 
18-Oct-2015 12:34:00 - INFO    :: MAIN : [VersionCheck] -  New version is available. You are 9 commits behind
18-Oct-2015 12:34:00 - DEBUG   :: MAIN : (getCommitDifferenceFromGit) - exiting with commit value of [9]
18-Oct-2015 12:34:00 - DEBUG   :: MAIN : Current Version [eef56e5d1e981f9899bc3b08bcb3c0ed55103800] - Latest remote version [b3082ba7f0c0721e71b4d6b93a5a0ae875f78119] - Install type [source]
18-Oct-2015 12:34:01 - INFO    :: MAIN : Starting LazyLibrarian on port: 5299
18-Oct-2015 12:34:10 - DEBUG   :: CP Server Thread-4 : (webServe-Update) - Performing update
18-Oct-2015 12:34:20 - INFO    :: MAIN : LazyLibrarian is updating...
18-Oct-2015 12:34:20 - INFO    :: MAIN : (update) Downloading update from: https://github.com/dobytang/lazylibrarian/tarball/master
18-Oct-2015 12:34:23 - INFO    :: MAIN : (update) Extracing fileC:\Program Files (x86)\LazyLibrarian\master
18-Oct-2015 12:34:24 - INFO    :: MAIN : (update) Deleting fileC:\Program Files (x86)\LazyLibrarian\master
18-Oct-2015 12:34:24 - DEBUG   :: MAIN : (updateVersionFile) Updating [C:\Program Files (x86)\LazyLibrarian\version.txt] with value [b3082ba7f0c0721e71b4d6b93a5a0ae875f78119]
18-Oct-2015 12:34:24 - INFO    :: MAIN : LazyLibrarian is restarting ...
18-Oct-2015 12:34:24 - INFO    :: MAIN : Restarting LazyLibrarian with ['C:\\Python27\\python.exe', 'C:\\Program Files (x86)\\LazyLibrarian\\LazyLibrarian.py', '--nolaunch']
```

**Comment by philborman** [comment]
The new version also uses zipfile, so you also need to pip install zipfile  
I will have a look at how to automate this, the current install system includes copies the libraries except for zipfile,unidecode,lxml, but if you run calibre/headphones/sickbeard etc you will end up with multiple copies of these libraries if each app has its own version. 
I think pip install is the way forward as it's the standard python installer, but how to do it cleanly? 
At present there isn't a "setup.py" perhaps we need one?

**Comment by philborman** [comment]
ForJaBaine, in windows command prompt...
python -m pip install zipfile  (do the same for unidecode and lxml)
unidecode is used for accented characters in authors names like John le Carrè
lxml is used for looking inside epub files, and is also needed for amazon books if and when I get around to looking at their api again

**Comment by theguardian** [comment]
Try the latest master. I included unidecode as a lib within the repo and remove lxml imports as it seems that xml.etree was already performing that function.

**Comment by maxcore** [comment]
fixit thx ! i close the issues!!

**Comment by philborman** [comment]
Doesn't actually fix the issue. 
unidecode references now all need changing from unidecode.unidecode() to unidecode() now library is in lib.unidecode
lxml.etree returns different data to xml.etree  so new books aren't found now.

**Comment by maxcore** [comment]
@philborman  i just talking about the restart after the update for the rest you have good point
