### ISSUE TITLE
postproc error

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#1519]
Post processing just started throwing errors.
Current Version: 310a964055b7711f4975709571f7da5afc48c168 

it also wont update from github

2018-07-26 09:41:05 | ERROR | POSTPROCESS | postprocess.py | processDir | 808 | Unhandled exception in processDir: Traceback (most recent call last):   File "/app/lazylibrarian/lazylibrarian/postprocess.py", line 645, in processDir     processMAGOPF(dest_file, book['BookID'], book['AuxInfo'], iss_id)   File "/app/lazylibrarian/lazylibrarian/postprocess.py", line 1821, in processMAGOPF     _ = processOPF(dest_path, data, global_name, overwrite=overwrite)   File "/app/lazylibrarian/lazylibrarian/postprocess.py", line 1899, in processOPF     opfinfo += '        %s\n' % int(round(data['BookRate'])) TypeError: a float is required
-- | -- | -- | -- | -- | -- | --

**Comment by Code-Slave** [comment]
just updated to latest and same issue postprocessing mags

**Comment by philborman** [comment]
Turn off magazine opf generating as a temporary measure, you can turn it back on  and libraryscan the mags again once its fixed. Should be simple to do, but I'm away until tomorrow.
