### ISSUE TITLE
Running searches now give errors on docker image after i got notifications about git

### ISSUE THREAD

**Issue by tahussle** [DobyTang/LazyLibrarian#1542]
400 Bad Request
Unexpected body parameters: utorrent_label, mag_img, deluge_label, rss_0_dlpriority, gen_host, newznab_0_audiocat, transmission_port, mag_type, rtorrent_label, author_img, gen2_dlpriority, transmission_pass, nzbget_category, reject_maxsize, kat_host, https_key, gen_dlpriority, pushover_keys, reject_minsize, mag_dest_file, max_pages, tpb_dlpriority, deluge_pass, proxy_host, search_bookinterval, imp_calibredb, gr_oauth_token, torznab_0_apilimit, banned_ext, ebook_dir, nma_apikey, logdir, book_api, http_user, sab_user, newznab_1_api, api_key, newznab_1_dispname, calibre_server, newznab_0_updated, goodreads_interval, tpb_host, telegram_token, reject_audio, gr_api, newznab_1_apilimit, newaudio_status, androidpn_url, audio_dir, newznab_0_magcat, newznab_1_generalsearch, email_to, fmt_sernum, imp_convert, cache_age, opds_username, slack_token, ebook_dest_file, transmission_user, torznab_0_dispname, sab_host, newznab_1_updated, tor_downloader_deluge, logsize, logfiles, nzbget_host, imp_monthlang, mag_relative, rtorrent_pass, prowl_apikey, androidpn_username, transmission_dir, http_pass, boxcar_token, newznab_0_magsearch, torznab_0_updated, qbittorrent_label, torznab_0_audiocat, search_maginterval, rtorrent_host, newauthor_audio, torznab_0_extended, pushover_device, nzbget_pass, torznab_0_audiosearch, pushbullet_token, torznab_0_api, email_smtp_server, sab_cat, imp_magopf, kat_dlpriority, nzbget_priority, rtorrent_user, gen2_host, reject_magsize, newznab_0_dlpriority, newznab_0_enabled, twitter_key, nzbget_user, bookstrap_theme, telegram_userid, tdl, fmt_series, email_smtp_port, calibre_pass, rtorrent_dir, add_series, wishlist_interval, nma_priority, newznab_0_generalsearch, https_cert, tdl_dlpriority, sab_pass, ebook_dest_folder, blacklist_failed, newznab_1_magcat, newznab_1_host, growl_password, admin_email, newauthor_status, ebook_type, gen2_search, dload_ratio, git_program, deluge_cert, email_smtp_password, add_author, mag_tab, usenet_retention, newznab_0_audiosearch, max_bookpages, newznab_0_dispname, task_age, newznab_1_booksearch, book_img, match_ratio, reject_minaudio, found_status, nzbget_port, prowl_priority, proxy_type, deluge_user, torznab_0_host, searchrss_interval, slack_url, imp_preprocess, deluge_dir, qbittorrent_pass, growl_host, synology_host, prefer_magnet, notfound_status, newznab_0_apilimit, transmission_host, versioncheck_interval, keep_seeding, gen_search, torznab_0_bookcat, torrent_dir, series_tab, wwt_host, pushover_apitoken, newznab_1_bookcat, max_wall, newznab_1_magsearch, zoo_host, reject_magmin, gr_secret, utorrent_host, toggles, newznab_1_name, pushbullet_deviceid, custom_script, imp_autoaddmag, gr_oauth_secret, sab_subdir, launch_browser, newznab_1_extended, torznab_0_booksearch, audiobook_dest_file, lime_host, date_format, loglimit, mag_dest_folder, numberofseeders, nzb_downloader_sabnzbd, sab_api, newznab_0_host, scan_interval, loglevel, newbook_status, imp_magcover, iss_format, qbittorrent_port, newznab_0_bookcat, email_from, zoo_dlpriority, imp_preflang, nzb_blackholedir, utorrent_user, rss_0_host, torznab_0_dlpriority, reject_maxaudio, qbittorrent_host, gb_api, synology_pass, deluge_port, newznab_0_name, opds_password, newznab_0_booksearch, newznab_1_audiosearch, http_port, fmt_sername, torznab_0_generalsearch, gr_wanted, lt_devkey, calibre_user, rss_0_dispname, newznab_1_audiocat, zoo, torznab_0_name, alternate_dir, synology_port, synology_dir, newznab_1_dlpriority, gr_owned, audiobook_type, tdl_host, qbittorrent_dir, sab_port, mag_age, deluge_host, pushover_priority, reject_mags, http_host, current_tab, kat, lime_dlpriority, torznab_0_magcat, utorrent_port, synology_user, reject_words, utf8, tpb, http_root, wwt_dlpriority, torznab_0_magsearch, qbittorrent_user, email_smtp_user, http_look, newznab_0_extended, imp_autoadd, newznab_0_api, audio_tab, download_dir, utorrent_pass, mag_single
Traceback (most recent call last):
  File "/app/lazylibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/lazylibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/lazylibrarian/cherrypy/_cpdispatch.py", line 67, in __call__
    raise sys.exc_info()[1]
HTTPError: (400, 'Unexpected body parameters: utorrent_label, mag_img, deluge_label, rss_0_dlpriority, gen_host, newznab_0_audiocat, transmission_port, mag_type, rtorrent_label, author_img, gen2_dlpriority, transmission_pass, nzbget_category, reject_maxsize, kat_host, https_key, gen_dlpriority, pushover_keys, reject_minsize, mag_dest_file, max_pages, tpb_dlpriority, deluge_pass, proxy_host, search_bookinterval, imp_calibredb, gr_oauth_token, torznab_0_apilimit, banned_ext, ebook_dir, nma_apikey, logdir, book_api, http_user, sab_user, newznab_1_api, api_key, newznab_1_dispname, calibre_server, newznab_0_updated, goodreads_interval, tpb_host, telegram_token, reject_audio, gr_api, newznab_1_apilimit, newaudio_status, androidpn_url, audio_dir, newznab_0_magcat, newznab_1_generalsearch, email_to, fmt_sernum, imp_convert, cache_age, opds_username, slack_token, ebook_dest_file, transmission_user, torznab_0_dispname, sab_host, newznab_1_updated, tor_downloader_deluge, logsize, logfiles, nzbget_host, imp_monthlang, mag_relative, rtorrent_pass, prowl_apikey, androidpn_username, transmission_dir, http_pass, boxcar_token, newznab_0_magsearch, torznab_0_updated, qbittorrent_label, torznab_0_audiocat, search_maginterval, rtorrent_host, newauthor_audio, torznab_0_extended, pushover_device, nzbget_pass, torznab_0_audiosearch, pushbullet_token, torznab_0_api, email_smtp_server, sab_cat, imp_magopf, kat_dlpriority, nzbget_priority, rtorrent_user, gen2_host, reject_magsize, newznab_0_dlpriority, newznab_0_enabled, twitter_key, nzbget_user, bookstrap_theme, telegram_userid, tdl, fmt_series, email_smtp_port, calibre_pass, rtorrent_dir, add_series, wishlist_interval, nma_priority, newznab_0_generalsearch, https_cert, tdl_dlpriority, sab_pass, ebook_dest_folder, blacklist_failed, newznab_1_magcat, newznab_1_host, growl_password, admin_email, newauthor_status, ebook_type, gen2_search, dload_ratio, git_program, deluge_cert, email_smtp_password, add_author, mag_tab, usenet_retention, newznab_0_audiosearch, max_bookpages, newznab_0_dispname, task_age, newznab_1_booksearch, book_img, match_ratio, reject_minaudio, found_status, nzbget_port, prowl_priority, proxy_type, deluge_user, torznab_0_host, searchrss_interval, slack_url, imp_preprocess, deluge_dir, qbittorrent_pass, growl_host, synology_host, prefer_magnet, notfound_status, newznab_0_apilimit, transmission_host, versioncheck_interval, keep_seeding, gen_search, torznab_0_bookcat, torrent_dir, series_tab, wwt_host, pushover_apitoken, newznab_1_bookcat, max_wall, newznab_1_magsearch, zoo_host, reject_magmin, gr_secret, utorrent_host, toggles, newznab_1_name, pushbullet_deviceid, custom_script, imp_autoaddmag, gr_oauth_secret, sab_subdir, launch_browser, newznab_1_extended, torznab_0_booksearch, audiobook_dest_file, lime_host, date_format, loglimit, mag_dest_folder, numberofseeders, nzb_downloader_sabnzbd, sab_api, newznab_0_host, scan_interval, loglevel, newbook_status, imp_magcover, iss_format, qbittorrent_port, newznab_0_bookcat, email_from, zoo_dlpriority, imp_preflang, nzb_blackholedir, utorrent_user, rss_0_host, torznab_0_dlpriority, reject_maxaudio, qbittorrent_host, gb_api, synology_pass, deluge_port, newznab_0_name, opds_password, newznab_0_booksearch, newznab_1_audiosearch, http_port, fmt_sername, torznab_0_generalsearch, gr_wanted, lt_devkey, calibre_user, rss_0_dispname, newznab_1_audiocat, zoo, torznab_0_name, alternate_dir, synology_port, synology_dir, newznab_1_dlpriority, gr_owned, audiobook_type, tdl_host, qbittorrent_dir, sab_port, mag_age, deluge_host, pushover_priority, reject_mags, http_host, current_tab, kat, lime_dlpriority, torznab_0_magcat, utorrent_port, synology_user, reject_words, utf8, tpb, http_root, wwt_dlpriority, torznab_0_magsearch, qbittorrent_user, email_smtp_user, http_look, newznab_0_extended, imp_autoadd, newznab_0_api, audio_tab, download_dir, utorrent_pass, mag_single')
Powered by CherryPy 3.6.0

-------------------------------------------------
i did a manual merge request but still no joy

git merge origin/master
Updating bb99887c..bbb36a41
Fast-forward
 data/interfaces/bookstrap/audio.html       |  11 -----------
 data/interfaces/bookstrap/author.html      |  11 -----------
 data/interfaces/bookstrap/base.html        |  47 +++++++++++++++++++++++++++++++++++++++++++----
 data/interfaces/bookstrap/books.html       |  11 -----------
 data/interfaces/bookstrap/index.html       |  33 ++++++++++++++++++++++++++++++---
 data/interfaces/bookstrap/managebooks.html |  24 ++++++++++++++++++++++++
 data/interfaces/bookstrap/members.html     |   4 +++-
 lazylibrarian/bookrename.py                |  59 ++++++++++++++++++++++++++++++-----------------------------
 lazylibrarian/dbupgrade.py                 |  26 +++++++++++++++++++++++---
 lazylibrarian/gb.py                        |   5 ++++-
 lazylibrarian/gr.py                        |  12 ++++++++----
 lazylibrarian/importer.py                  |   3 ++-
 lazylibrarian/opds.py                      |   4 ++--
 lazylibrarian/webServe.py                  |  24 +++++++++++++++++++++++-
 lib/tinytag.note                           |  15 +++++++++++++++
 lib/tinytag.py                             | 114 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------

**Comment by tahussle** [comment]
Issue was with   using microsoft edge as a browser
