### ISSUE TITLE
Magazine or Book With éèàêëęėē character Give Error

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#158]
When i add 'Compétence Mac' magazine i get error ->
```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/volume1/@appstore/lazylibrarian/share/LazyLibrarian/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/volume1/@appstore/lazylibrarian/share/LazyLibrarian/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/lazylibrarian/share/LazyLibrarian/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/lazylibrarian/share/LazyLibrarian/lazylibrarian/webServe.py", line 841, in searchForMag
    logger.debug("Searching for magazine with title: " + str(bookid));
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
Powered by CherryPy 3.2.0

````
in my log

````
2015-10-24 14:19:34	INFO	[NewzNabPlus] searchType [mag] with Host [https://api.dognzb.cr] using api [***************************************] for item [{'searchterm': 'Competence Mac', 'bookid': u'Comp\xe9tence Mac'}]

```

**Comment by maxcore** [comment]
thx for the fix 009019d
