### ISSUE TITLE
Magzine library scan error

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#1617]
Latest revision, on thraxis docker

I go into a mag dir and do a library scan

  | Unhandled exception in magazineScan: Traceback (most recent call last):   File "/app/lazylibrarian/lazylibrarian/magazinescan.py", line 85, in magazineScan     mag_path = os.path.dirname(match['LatestCover'])   File "/usr/lib/python2.7/posixpath.py", line 122, in dirname     i = p.rfind('/') + 1 AttributeError: 'NoneType' object has no attribute 'rfind'
-- | --

**Comment by Code-Slave** [comment]
When i switched dockers i messed up mag dir so thats why it found no mags. After i fixed that the scan worked from the main page. This happened when i went in a specific mag (it had issues and covers) and hit library scan. Will test in a bit
