### ISSUE TITLE
Getting Error Unhandled exception in search_rss_book about every 20 minutes in logs

### ISSUE THREAD

**Issue by mstrdraco** [DobyTang/LazyLibrarian#1628]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

getting the following about every 20 minutes. 

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2492879/debug.zip)

2018-10-18 12:44:14 | ERROR | Unhandled exception in search_rss_book: Traceback (most recent call last): File "C:\ProgramData\LazyLibrarian\lazylibrarian\searchrss.py", line 302, in search_rss_book resultlist, nproviders = IterateOverRSSSites() ValueError: too many values to unpack
-- | -- | --

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by mstrdraco** [comment]
2018-10-18 13:04:14 | ERROR | SEARCHALLRSS | searchrss.py | search_rss_book | 370 | Unhandled exception in search_rss_book: Traceback (most recent call last): File "C:\ProgramData\LazyLibrarian\lazylibrarian\searchrss.py", line 302, in search_rss_book resultlist, nproviders = IterateOverRSSSites() ValueError: too many values to unpack
-- | -- | -- | -- | -- | -- | --

**Comment by jcal22** [comment]
Line 565 in providers.py is trying to return three variables:

return resultslist, providers, ''.join(set(dltypes))

Line 302 in searchrss.py is only looking for two variables.

**Comment by philborman** [comment]
The 3rd param isn't needed there, should have a _ 
Will be fixed shortly, just adding some other changes
