### ISSUE TITLE
AttributeError: 'module' object has no attribute 'NEWZNAB_HOST'

### ISSUE THREAD

**Issue by arogl** [DobyTang/LazyLibrarian#177]
@philborman

Getting the above error as well as an error with nzbget

```
14-Nov-2015 16:49:01 - DEBUG :: CP Server Thread-4 : Config file has been updated
14-Nov-2015 16:49:16 - DEBUG :: CP Server Thread-4 : Searching for book with id: 13515848
14-Nov-2015 16:49:16 - DEBUG :: SEARCHNZBBOOKS : [IterateOverNewzNabSites] - NewzNab0
14-Nov-2015 16:49:16 - DEBUG :: SEARCHTORBOOKS : [IterateOverTorrentSites] - KAT
14-Nov-2015 16:49:16 - INFO :: SEARCHNZBBOOKS : [NewzNabPlus] searchType [book] with Host [https://www.usenet-crawler.com/] mode [nzb] using api [XXXXX] for item [{'searchterm': 'A E Rought Broken', 'bookName': u'Broken (Broken, #1)', 'authorName': u'A.E. Rought', 'bookid': u'13515848'}]
14-Nov-2015 16:49:16 - DEBUG :: SEARCHNZBBOOKS : [NewzNabPlus] - Search parameters set to {'author': 'A.E. Rought', 'apikey': u'XXXXX', 't': 'book', 'cat': 7020, 'title': 'Broken (Broken 1)'}
14-Nov-2015 16:49:17 - WARNING :: SEARCHTORBOOKS : http://kat.cr/usearch/A%20E%20Rought%20Broken/?category=books&field=seeders&rss=1&sorder=desc
14-Nov-2015 16:49:17 - WARNING :: SEARCHTORBOOKS : Error fetching data from KAT: HTTP Error 404: Not Found
14-Nov-2015 16:49:17 - INFO :: SEARCHTORBOOKS : Searching for type book failed to find any books...moving to general search
14-Nov-2015 16:49:17 - DEBUG :: SEARCHTORBOOKS : [IterateOverTorrentSites] - KAT
14-Nov-2015 16:49:18 - DEBUG :: SEARCHNZBBOOKS : Parsing results from <a href="https://www.usenet-crawler.com//api?author=A.E.+Rought&apikey=XXXXX&t=book&cat=7020&title=Broken+%28Broken+1%29">https://www.usenet-crawler.com/</a>
14-Nov-2015 16:49:18 - INFO :: SEARCHNZBBOOKS : Found 0 nzb at https://www.usenet-crawler.com/ for: A E Rought Broken
14-Nov-2015 16:49:18 - INFO :: SEARCHNZBBOOKS : Searching for type book failed to find any books...moving to general search
14-Nov-2015 16:49:18 - DEBUG :: SEARCHNZBBOOKS : [IterateOverNewzNabSites] - NewzNab0
14-Nov-2015 16:49:18 - INFO :: SEARCHNZBBOOKS : [NewzNabPlus] searchType [general] with Host [https://www.usenet-crawler.com/] mode [nzb] using api [XXXXX] for item [{'searchterm': 'A E Rought Broken', 'bookName': u'Broken (Broken, #1)', 'authorName': u'A.E. Rought', 'bookid': u'13515848'}]
14-Nov-2015 16:49:18 - DEBUG :: SEARCHNZBBOOKS : [NewzNabPlus] - Search parameters set to {'q': 'A E Rought Broken', 'apikey': u'XXXXX', 't': 'search', 'extended': 1}
14-Nov-2015 16:49:19 - WARNING :: SEARCHTORBOOKS : http://kat.cr/usearch/A%20E%20Rought%20Broken/?category=books&field=seeders&rss=1&sorder=desc
14-Nov-2015 16:49:19 - WARNING :: SEARCHTORBOOKS : Error fetching data from KAT: HTTP Error 404: Not Found
14-Nov-2015 16:49:19 - DEBUG :: SEARCHTORBOOKS : Adding book A E Rought Broken to queue.
14-Nov-2015 16:49:19 - INFO :: SEARCHTORBOOKS : TORSearch for Wanted items complete
14-Nov-2015 16:49:23 - DEBUG :: SEARCHNZBBOOKS : Parsing results from <a href="https://www.usenet-crawler.com//api?q=A+E+Rought+Broken&apikey=XXXXX&t=search&extended=1">https://www.usenet-crawler.com/</a>
14-Nov-2015 16:49:40 - DEBUG :: SEARCHNZBBOOKS : [NewzNabPlus] - result fields from NZB are {'bookid': u'13515848', 'nzbmode': 'nzb', 'nzbdate': 'Sun, 23 Feb 2014 17:35:58 +0100', 'nzbtitle': 'A E Rought - [Broken 01] - Broken (v4.0) (epub)', 'nzbsize': '341209', 'nzburl': 'https://www.usenet-crawler.com/getnzb/2e2bbb1beb7a4a77ffa85a8812e66420.nzb&i=195985&r=XXXXX', 'nzbprov': u'https://www.usenet-crawler.com/'}
14-Nov-2015 16:49:40 - DEBUG :: SEARCHNZBBOOKS : [NewzNabPlus] - result fields from NZB are {'bookid': u'13515848', 'nzbmode': 'nzb', 'nzbdate': 'Fri, 18 Oct 2013 02:16:52 +0200', 'nzbtitle': 'A E Rought - [Broken 02] - Tainted (epub)', 'nzbsize': '830139', 'nzburl': 'https://www.usenet-crawler.com/getnzb/ec7748e6a56e0a9f5a6d5d52b314bc84.nzb&i=195985&r=XXXXX', 'nzbprov': u'https://www.usenet-crawler.com/'}
14-Nov-2015 16:49:40 - DEBUG :: SEARCHNZBBOOKS : [NewzNabPlus] - result fields from NZB are {'bookid': u'13515848', 'nzbmode': 'nzb', 'nzbdate': 'Tue, 19 Feb 2013 13:09:31 +0100', 'nzbtitle': 'A E Rought - Broken (mobi)', 'nzbsize': '381065', 'nzburl': 'https://www.usenet-crawler.com/getnzb/81e0a4e2e21b8d5154724f3e5e9522e6.nzb&i=195985&r=XXXXX', 'nzbprov': u'https://www.usenet-crawler.com/'}
14-Nov-2015 16:49:40 - DEBUG :: SEARCHNZBBOOKS : [NewzNabPlus] - result fields from NZB are {'bookid': u'13515848', 'nzbmode': 'nzb', 'nzbdate': 'Thu, 17 Jan 2013 21:38:10 +0100', 'nzbtitle': 'A E Rought - Broken (epub)', 'nzbsize': '338276', 'nzburl': 'https://www.usenet-crawler.com/getnzb/d440fb0a07587a76f7dc788e594a44a1.nzb&i=195985&r=XXXXX', 'nzbprov': u'https://www.usenet-crawler.com/'}
14-Nov-2015 16:49:40 - INFO :: SEARCHNZBBOOKS : Found 4 nzb at https://www.usenet-crawler.com/ for: A E Rought Broken
14-Nov-2015 16:49:40 - DEBUG :: SEARCHNZBBOOKS : searchterm A E Rought Broken
14-Nov-2015 16:49:40 - DEBUG :: SEARCHNZBBOOKS : nzbName a e rought broken broken v epub
14-Nov-2015 16:49:40 - DEBUG :: SEARCHNZBBOOKS : NZB Title Match %: 71
14-Nov-2015 16:49:40 - DEBUG :: SEARCHNZBBOOKS : nzbName a e rought broken tainted epub
14-Nov-2015 16:49:40 - DEBUG :: SEARCHNZBBOOKS : NZB Title Match %: 72
14-Nov-2015 16:49:40 - DEBUG :: SEARCHNZBBOOKS : nzbName a e rought broken mobi
14-Nov-2015 16:49:40 - DEBUG :: SEARCHNZBBOOKS : NZB Title Match %: 87
14-Nov-2015 16:49:40 - INFO :: SEARCHNZBBOOKS : Found NZB: A E Rought - Broken (mobi)
14-Nov-2015 16:49:40 - DEBUG :: SEARCHNZBBOOKS : Requesting URL via GET method: https://www.usenet-crawler.com/getnzb/81e0a4e2e21b8d5154724f3e5e9522e6.nzb&i=195985&r=XXXXX
14-Nov-2015 16:49:43 - DEBUG :: SEARCHNZBBOOKS : Successfully connected to NZBget
14-Nov-2015 16:49:43 - INFO :: SEARCHNZBBOOKS : Sending NZB to NZBget
14-Nov-2015 16:49:43 - DEBUG :: SEARCHNZBBOOKS : URL: http://YYY:ZZZ@localhost:6789/xmlrpc
14-Nov-2015 16:49:44 - DEBUG :: SEARCHNZBBOOKS : NZB Version 16
14-Nov-2015 16:49:45 - ERROR :: SEARCHNZBBOOKS : Connect Error to NZBget: could not add A.E. Rought - Broken (Broken, #1) LL.(13515848).nzb to the queue: <Fault 2: 'Invalid parameter (AddTop)'>
Exception in thread SEARCHNZBBOOKS:
Traceback (most recent call last):
  File "c:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "c:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "f:\Git\LazyLibrarian\lazylibrarian\searchnzb.py", line 136, in search_nzb_book
    snatch = NZBDownloadMethod(bookid, nzbprov, nzbTitle, nzburl)
  File "f:\Git\LazyLibrarian\lazylibrarian\searchnzb.py", line 213, in NZBDownloadMethod
    logger.error(u'Failed to download nzb @ <a href="%s">%s</a>' % (nzburl, lazylibrarian.NEWZNAB_HOST))
AttributeError: 'module' object has no attribute 'NEWZNAB_HOST'
```
Rgds Andrew

**Comment by philborman** [comment]
Found and fixed the attribute error, it's trying to report the earlier 
error from nzbget, 'Invalid parameter (AddTop), but doesn't know who the 
host was. It's not lazylibrarian.NEWZNAB_HOST, should be nzbprov
searchnzb.py line 343 if you want a temporary fix.

The earlier "Invalid parameter (AddTop)" needs fixing, but I have no 
knowledge of nzbget.
There are comments in the code about different versions of nzbget 
behaving differently,
v14 apparently doesn't like parameter autoAdd. v16 seems not to like AddTop.

There are also a couple of 404 errors in your log fetching data from 
KAT, these need looking into as well. The search term used in KAT looks 
ok. I've only used KAT for magazines, will try books here and see if I 
can get more info.

||||

**Comment by philborman** [comment]
I think I have found the AddTop error, would you be interested in trying a test version to see if it works before I push the fix out.  If so, email me back, and let me know what system you are running on (windows/mac/linux) and if you are happy to make a small edit to one of the lazylibrarian files. Thanks, Phil

**Comment by arogl** [comment]
[**@philborman**](https://github.com/philborman) commented on [15 Nov 2015, 12:56 AM AEST](https://github.com/DobyTang/LazyLibrarian/issues/177#issuecomment-156709096 "2015-11-14T14:56:36Z - Replied by Github Comment Enhancer"):
> I think I have found the AddTop error, would you be interested in trying a test version to see if it works before I push the fix out.  If so, email me back, and let me know what system you are running on (windows/mac/linux) and if you are happy to make a small edit to one of the lazylibrarian files. Thanks, Phil
@philborman happy to make modifictions. I can also run off your test version if needed.  I am running on Windows 10, Python 2.7.10, and NZBGET v16.

Thanks for looking into this issue so quickly.

**Comment by arogl** [comment]
@philborman the 404 error with kat.cr is definitely a not found as putting the search term in gives a not found on kat.

Also should you move kat from http to https?

**Comment by philborman** [comment]
I think the 404 error needs catching and replacing with a normal message
from the program saying "no books found"  or something similar.  The 404
message makes it look like a fault rather than a normal occurrence.

The https for kat is user configurable,  in the config settings it says
kat.cr   user can change this to https <https://kat.cr>:// <https://kat.cr>
kat.cr  Default is http if not specified in the name. I might add more
torrent hosts later,  not all need https.

The nzbget fault is simple,  i think.
In file nzbget.py, line 109 it has "False",  "False"
This needs changing to False,  False   (no quotes)

Nzbget needs a boolean true/false or 1/0  not a string.

You could edit this yourself and try it,  or there is a test version with
this fix included at https://github.com/philborman/LazyLibrarian/

Let me know how you get on, thanks.

**Comment by arogl** [comment]
Hi,

By editing the file as described I can now snatch books via nzbget.

On the config screen for providers I only have a a tick box for KAT and an input box for a host name. I have added https:// to that box and all is now good.

Rgds Andrew.

**Comment by philborman** [comment]
Thanks for letting me know
I think the issue with version 14 should also be fixed by this,  your
version 16 failed because of the first "False",  version 14 was failing on
the second one.

Thanks for your help

**Comment by philborman** [comment]
This can be  marked closed now

**Comment by tofagerl** [comment]
Was this fixed in master?
