### ISSUE TITLE
Post processing not working.

### ISSUE THREAD

**Issue by nncrypted** [DobyTang/LazyLibrarian#183]
21-Nov-2015 23:16:20 - DEBUG :: POSTPROCESS : Removing existing tree
21-Nov-2015 23:16:20 - DEBUG :: POSTPROCESS : Attempting to copy/move tree
Exception in thread POSTPROCESS:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/LazyLibrarian/lazylibrarian/postprocess.py", line 97, in processDir
    processBook = processDestination(pp_path, dest_path, authorname, bookname, global_name, book['BookID'])
  File "/opt/LazyLibrarian/lazylibrarian/postprocess.py", line 260, in processDestination
    shutil.move(pp_path, dest_path)
  File "/usr/lib/python2.7/shutil.py", line 298, in move
    copytree(src, real_dst, symlinks=True)
  File "/usr/lib/python2.7/shutil.py", line 182, in copytree
    srcname = os.path.join(src, name)
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 25: ordinal not in range(128)

**Comment by nncrypted** [comment]
Any of the above make sense.

**Comment by philborman** [comment]
unicode error on a filename, either pp_path or dest_path has a character that the "move" code doesnt like. I have added some extra debugging messages to the version in my git if you could try it and report back? will still fail, but should tell us why.

**Comment by nncrypted** [comment]
Your's worked quite well tile I got this error. Some of the errors were permissions in my file folders so I've fixed those. 

22-Nov-2015 14:35:45 - DEBUG :: POSTPROCESS : Attempting to copy/move tree
Exception in thread POSTPROCESS:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/LazyLibrarian/lazylibrarian/postprocess.py", line 187, in processDir
    processBook = processDestination(pp_path, dest_path, authorname, bookname, global_name, bookID)
  File "/opt/LazyLibrarian/lazylibrarian/postprocess.py", line 262, in processDestination
    shutil.move(pp_path, dest_path)
  File "/usr/lib/python2.7/shutil.py", line 298, in move
    copytree(src, real_dst, symlinks=True)
  File "/usr/lib/python2.7/shutil.py", line 182, in copytree
    srcname = os.path.join(src, name)
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 25: ordinal not in range(128)

**Comment by philborman** [comment]
There should be a few more debug lines just before this log section,
dest_path = xxx xxx
pp_path = xxx xxx
xxx does not exist    or
xxx already exists

could you post that section of log please.
thanks,
Phil

**Comment by nncrypted** [comment]
22-Nov-2015 14:35:45 - DEBUG :: POSTPROCESS : Removing existing tree
22-Nov-2015 14:35:45 - DEBUG :: POSTPROCESS : Attempting to copy/move tree

**Comment by philborman** [comment]
Anything in the log like this....

lNFO :: POSTPROCESS : Found folder %s.'

**Comment by philborman** [comment]
What messages do you get if you set 'Keep Original Files' in 
config/search & processing

**Comment by nncrypted** [comment]
I can't right now I've got other issues unrelated I need to deal with. This will need to go on the back burner. I don't even read ebooks LOL I'm just intrigued in how this works and like reading to conversations when everyone is collaborating. You all are very smart people.

**Comment by nncrypted** [comment]
Everything works great now.
