### ISSUE TITLE
Searching Goodreads never returns info

### ISSUE THREAD

**Issue by hidefog** [DobyTang/LazyLibrarian#202]
I never get a response when searching for titles or authors using Goodreads through lazylibrarian with my API.  Google searching works OK.

This is what is what shows on the console when searching.

Exception in thread GR-SEARCH:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/LazyLibrarian/lazylibrarian/gr.py", line 96, in find_results
    rootxml = sourcexml.getroot()
NameError: global name 'sourcexml' is not defined

**Comment by philborman** [comment]
Ah, silly error. That line is redundant, just comment it out. 
Fixed in the version just posted.
