### ISSUE TITLE
LL missing section?

### ISSUE THREAD

**Issue by mgaulton** [DobyTang/LazyLibrarian#245]
I noticed that my LL didn't start up and discovered the below. i nuked and recloned, still not working. 
I haven't changed the ini, i assume something was added that I'm now missing?

Traceback (most recent call last):
  File "./LazyLibrarian.py", line 179, in <module>
    main()
  File "./LazyLibrarian.py", line 125, in main
    lazylibrarian.initialize()
  File "/opt/LazyLibrarian-1-master/lazylibrarian/__init__.py", line 517, in initialize
    add_rss_slot()
  File "/opt/LazyLibrarian-1-master/lazylibrarian/__init__.py", line 861, in add_rss_slot
    if len(CFG.get('RSS_%i' % int(count-1), 'HOST')):
  File "/usr/lib64/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'RSS_-1'

**Comment by mgaulton** [comment]
I removed my config.ini in the hopes of creating a clean file with all options and then got this.

Traceback (most recent call last):
  File "./LazyLibrarian.py", line 179, in <module>
    main()
  File "./LazyLibrarian.py", line 125, in main
    lazylibrarian.initialize()
  File "/opt/LazyLibrarian-1-master/lazylibrarian/__init__.py", line 467, in initialize
    add_newz_slot()
  File "/opt/LazyLibrarian-1-master/lazylibrarian/__init__.py", line 833, in add_newz_slot
    if len(CFG.get('Newznab%i' % int(count-1), 'HOST')):
  File "/usr/lib64/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'Newznab-1'

**Comment by philborman** [comment]
Ah - lots of changes in this bit of the code, some of the option names have changed. There is code to convert old names to new ones, but I need to add a bit for checking if non-existent option in config.
For now, if you manually edit the config.ini and add this to the end of the file it should go away, sorry about that...

[Newznab0]
enabled = False
host = 
api = 

[Torznab0]
enabled = False
host =
api =

[RSS_0]
enabled = False
host =
user = 
pass =

**Comment by mgaulton** [comment]
no worries, I was just puzzled lol
Thanks.

**Comment by mgaulton** [comment]
That worked a treat. Ty

**Comment by philborman** [comment]
Yeah,  I'm getting quite good at fixing bugs I've introduced ;-)
