### ISSUE TITLE
After update

### ISSUE THREAD

**Issue by nncrypted** [DobyTang/LazyLibrarian#259]
Traceback (most recent call last):
  File "LazyLibrarian.py", line 179, in <module>
    main()
  File "LazyLibrarian.py", line 125, in main
    lazylibrarian.initialize()
  File "/opt/LazyLibrarian/lazylibrarian/__init__.py", line 635, in initialize
    BOOKSTRAP_THEMELIST = build_bookstrap_themes()
  File "/opt/LazyLibrarian/lazylibrarian/__init__.py", line 890, in build_bookstrap_themes
    resp = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1219, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>

**Comment by famewolf** [comment]
Is there a way to pull the PREVIOUS to most recent commits version into our jails (I'm using it on freenas) to get the plugin back up and running? I think I was only 4 commits behind.

**Comment by philborman** [comment]
Easy quick fix is to change the line
BOOKSTRAP_THEMELIST = build_bookstrap_themes()
to BOOKSTRAP_THEMELIST = []      
(empty square brackets)  while  look into this. Works on my Linux box and Raspberry Pi, don't have a NAS to test on.

**Comment by famewolf** [comment]
Change it WHERE exactly?

**Comment by philborman** [comment]
Sorry, it says in the log above, 

File "/opt/LazyLibrarian/lazylibrarian/init.py", line 635, in initialize
BOOKSTRAP_THEMELIST = build_bookstrap_themes()

**Comment by famewolf** [comment]
Thanks.  I changed it but all I get is an error about unexpected indent.   I don't see any of those but I may have moved the line when I commented it out originally.

**Comment by philborman** [comment]
if you don't mind trying something, I'm wondering if it simply doesn't like the https:// address for bootstrap. It's in the same file URL = 'https://bootswatch.com/api/3.json'
Could you try taking the 's' out so it's just http://bootswatch.com/api/3.json
and see if it still fails? Seems to only be a problem on NAS devices, and I don't have one to test.

The next version will have a temporary fix included anyway, but would be good to know how to fix it for real. Might be as simple as not using https

**Comment by nncrypted** [comment]
Tried all this doesn't work I'm running Open Media Vault based on debian. I merged the pull request. But not going to update mine for a bit

**Comment by nncrypted** [comment]
After changing https to http I get the following: And I have NOT applied the current merge.

Traceback (most recent call last):
  File "LazyLibrarian.py", line 179, in <module>
    main()
  File "LazyLibrarian.py", line 125, in main
    lazylibrarian.initialize()
  File "/opt/LazyLibrarian/lazylibrarian/__init__.py", line 635, in initialize
    BOOKSTRAP_THEMELIST = build_bookstrap_themes()
  File "/opt/LazyLibrarian/lazylibrarian/__init__.py", line 890, in build_bookstrap_themes
    resp = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1211, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by philborman** [comment]
ok many thanks for trying it.  It wouldn't be that simple, would it :-)

The current merge makes the problem disappear, but only by error 
trapping it so the program doesn't stop.
At least we might get a more useful error message back from it.

It can't really be urllib2 as that's used a lot in LazyLibrarian, eg in 
the code that checks for version updates.
It has to be something to do with the way this section of code is 
calling it.
I need to think about it...

You _might_ find auto-update doesn't work straight away as you kindly 
modified the init.py file for me,
to revert it, log into your NAS with ssh,  cd  /opt/LazyLibrarian/
and then git checkout lazylibrarian/__init__.py   (with the underscores 
that get stripped out)
that will reverse your changes. Then the auto-update will work properly 
again.

**Comment by nncrypted** [comment]
Just used git pull and it pulled an nice new clean install of LL
