### ISSUE TITLE
UnicodeEncodeError when adding download dir with "é" accent

### ISSUE THREAD

**Issue by Elektro121** [DobyTang/LazyLibrarian#291]
Hello everyone !

I tried to add a dowload folder and a drop-in torrent folder in the application, i received this message. Tried to download a book, it worked, but in the log every é is replaced by a simple e. The error seem not blocking.

> Traceback (most recent call last):
  File "/opt/lazylibrarian/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/opt/lazylibrarian/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/lazylibrarian/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/lazylibrarian/lazylibrarian/webServe.py", line 261, in configUpdate
    lazylibrarian.config_write()
  File "/opt/lazylibrarian/lazylibrarian/__init__.py", line 852, in config_write
    CFG.write(configfile)
  File "/usr/lib/python2.7/ConfigParser.py", line 412, in write
    key = " = ".join((key, str(value).replace('\n', '\n\t')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 24: ordinal not in range(128)

**Comment by philborman** [comment]
Yes, we have had a lot of problems with accented characters and unicode, not just reading and writing, but also matching names with and without accents, so it seems simpler and more reliable to drop the accents and replace with plain letters. I will add code to do this in the config section too.

**Comment by philborman** [comment]
Added this to the latest version, should be fixed now. can you check, and close the issue if its working. Thanks.

**Comment by JaBaine** [comment]
this may not be the same issue but for the author China Miéville the link to the author shows up as http://localhost:5299/authorPage?AuthorName=China%20Mi%C3%A9ville 

and I get  500 Internal Server Error

`Traceback (most recent call last):
  File "C:\Program Files (x86)\LazyLibrarian\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "C:\Program Files (x86)\LazyLibrarian\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Program Files (x86)\LazyLibrarian\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\LazyLibrarian\lazylibrarian\webServe.py", line 346, in authorPage
    return serve_template(templatename="author.html", title=urllib.quote(author['AuthorName']),
  File "C:\Python27\lib\urllib.py", line 1303, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe9'`

**Comment by philborman** [comment]
No, that's an entirely separate bug :-)
Fixed now.

**Comment by philborman** [comment]
Can this be closed now?

**Comment by knobunc** [comment]
I tried to add Hergé (for the Tintin books) and while the author is added, it is stuck forever loading...

**Comment by philborman** [comment]
Yes the logger doesn't like accents.  Thought it should be fixed but it's
still not happy.  Will be back home tomorrow,  won't take long to fix i
hope.

**Comment by knobunc** [comment]
You are awesome.  Thanks!
