### ISSUE TITLE
Config Screen After Newest Commit

### ISSUE THREAD

**Issue by lurknyou** [DobyTang/LazyLibrarian#315]
Anytime I select config at the top I get this error.

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "c:\lazylibrarian\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "c:\lazylibrarian\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\lazylibrarian\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\lazylibrarian\lazylibrarian\webServe.py", line 78, in config
    'MANUAL':       formatter.check_int(provider['Manual'], 0)
  File "c:\lazylibrarian\lazylibrarian\formatter.py", line 106, in check_int
    return int(var)
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by maxcore** [comment]
![capture d ecran 2016-03-11 15 28 45](https://cloud.githubusercontent.com/assets/4043787/13714671/264704e4-e79e-11e5-80cf-69d7c926e93b.png)
same for me

**Comment by philborman** [comment]
oops sorry, uploaded an incomplete version. Corrected now, just waiting for it to be pulled into the main repo.
