### ISSUE TITLE
Error importing author books

### ISSUE THREAD

**Issue by vader083** [DobyTang/LazyLibrarian#369]
27-May-2016 16:41:24 - DEBUG :: DBIMPORT : [Dan Simmons] Processing info for authorID: 2687
27-May-2016 16:41:24 - DEBUG :: DBIMPORT : [Dan Simmons] Now processing books with Google Books API
27-May-2016 16:41:24 - DEBUG :: DBIMPORT : CacheHandler: Returning CACHED response for https://www.googleapis.com/books/v1/volumes?q=inauthor%3A%22Dan%20Simmons%22&startIndex=0&printType=books&key=?????&maxResults=40
27-May-2016 16:41:24 - DEBUG :: DBIMPORT : Found 241 results for Dan Simmons
Exception in thread DBIMPORT:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7.9/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7.9/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/lazylibrarian/lazylibrarian/importer.py", line 54, in addAuthorToDB
    book_api.get_author_books(authorid, authorname, refresh=refresh)
  File "/opt/lazylibrarian/lazylibrarian/gb.py", line 534, in get_author_books
    bookid)
NameError: global name 'bookid' is not defined

**Comment by philborman** [comment]
Sorry, away from home for a few days. Found the problem, but I can´t get to fix it for maybe a week.
Looks like it´s been lurking there unreported for months!

If you want to fix it before I can, 
In lazylibrarian/gb.py  line 531, just below the line 
        bookrate = float(bookrate) 
put
        bookid = item['id']

Python is fussy about whitespace, you need to use enough spaces on the left of the line so it lines up with the bookrate line.

**Comment by vader083** [comment]
This fix worked but with the latest update I'm just seeing it hang.

2016-07-18 09:22:59	DEBUG	[Judy Blume] Now processing books with Google Books API
2016-07-18 09:22:58	DEBUG	[Judy Blume] Processing info for authorID: 12942

**Comment by philborman** [comment]
Thanks, found it.
Just submitted a fix. googlebooks needs unaccented author names.
