### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by perezbalen** [DobyTang/LazyLibrarian#399]
Hi

Just installed on Mac OS X 10.11.5, and I'm getting this:

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Applications/LazyLibrarian/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/Applications/LazyLibrarian/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Applications/LazyLibrarian/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Applications/LazyLibrarian/lazylibrarian/webServe.py", line 729, in addBook
    if AuthorI:
NameError: global name 'AuthorI' is not defined
Powered by CherryPy 3.2.0
```

This happens when I try to add a book  (magazines seems to be ok, though).

Branch: 
master Current Version: ac818e999b6bb8877e09b5253764db5d5e19cd4c : 
Latest Version: ac818e999b6bb8877e09b5253764db5d5e19cd4c

This is the log:

```
2016-07-06 17:19:57	INFO	TORSearch for Wanted items complete, found 0 books
2016-07-06 17:19:57	DEBUG	Searches for Jeffrey Michael Bays Between the Scenes What Every Film Director Writer and Editor Should Know About Scene Transitions returned no results.
2016-07-06 17:19:57	DEBUG	No torrent's found for Jeffrey Michael Bays Between the Scenes What Every Film Director, Writer, and Editor Should Know About Scene Transitions using searchtype author
2016-07-06 17:19:57	DEBUG	Found 0 results from KAT for Jeffrey Michael Bays Between the Scenes What Every Film Director Writer and Editor Should Know About Scene Transitions
2016-07-06 17:19:57	DEBUG	No results found from KAT for Jeffrey Michael Bays Between the Scenes What Every Film Director Writer and Editor Should Know About Scene Transitions
2016-07-06 17:19:56	DEBUG	[IterateOverTorrentSites] - KAT
2016-07-06 17:19:56	DEBUG	No torrent's found for Jeffrey Michael Bays Between the Scenes What Every Film Director, Writer, and Editor Should Know About Scene Transitions using searchtype general
2016-07-06 17:19:56	DEBUG	Found 0 results from KAT for Jeffrey Michael Bays Between the Scenes What Every Film Director Writer and Editor Should Know About Scene Transitions
2016-07-06 17:19:56	DEBUG	No results found from KAT for Jeffrey Michael Bays Between the Scenes What Every Film Director Writer and Editor Should Know About Scene Transitions
2016-07-06 17:19:55	DEBUG	[IterateOverTorrentSites] - KAT
2016-07-06 17:19:55	DEBUG	No torrent's found for Jeffrey Michael Bays Between the Scenes What Every Film Director, Writer, and Editor Should Know About Scene Transitions using searchtype book
2016-07-06 17:19:55	DEBUG	Found 0 results from KAT for Jeffrey Michael Bays Between the Scenes What Every Film Director Writer and Editor Should Know About Scene Transitions
2016-07-06 17:19:55	DEBUG	No results found from KAT for Jeffrey Michael Bays Between the Scenes What Every Film Director Writer and Editor Should Know About Scene Transitions
2016-07-06 17:19:54	DEBUG	Searching for book with id: 18051735
2016-07-06 17:19:54	DEBUG	[IterateOverTorrentSites] - KAT
2016-07-06 17:19:54	INFO	TOR Searching for 1 book
2016-07-06 17:19:54	DEBUG	getBookWork: Returning Cached WorkPage for 18051735 Workpage
2016-07-06 17:19:54	DEBUG	getBookWork: Returning Cached WorkPage for 18051735 Series
2016-07-06 17:19:54	DEBUG	Updated cover for Between the Scenes What Every Film Director, Writer, and Editor Should Know About Scene Transitions to images/cache/18051735.jpg
2016-07-06 17:19:54	DEBUG	getBookCover: Caching librarything cover for 18051735
2016-07-06 17:19:52	DEBUG	getBookWork: Caching response for /Applications/LazyLibrarian/cache/WorkCache/18051735.html
2016-07-06 17:19:51	DEBUG	Between the Scenes What Every Film Director, Writer, and Editor Should Know About Scene Transitions added to the books database
2016-07-06 17:19:51	DEBUG	[Jeffrey Michael Bays] Processing info for authorID: 7126884
2016-07-06 17:19:51	DEBUG	CacheHandler: Storing XML for http://www.goodreads.com/author/show/7126884.xml?key=ckvsiSDsuqh7omh74ZZ6Q
2016-07-06 17:19:51	DEBUG	CacheHandler: Storing XML for http://www.goodreads.com/api/author_url/Jeffrey%20Michael%20Bays?key=ckvsiSDsuqh7omh74ZZ6Q
2016-07-06 17:19:51	DEBUG	Searching for author with name: Jeffrey Michael Bays
2016-07-06 17:19:51	DEBUG	Book Between the Scenes: What Every Film Director, Writer, and Editor Should Know About Scene Transitions language does not match preference
2016-07-06 17:19:51	DEBUG	CacheHandler: Storing XML for https://www.goodreads.com/book/show/18051735?key=ckvsiSDsuqh7omh74ZZ6Q
2016-07-06 17:19:42	DEBUG	The GoodReads API was hit 0 times for keyword between the scenes
2016-07-06 17:19:42	DEBUG	Found 20 results with keyword: between the scenes
2016-07-06 17:19:42	DEBUG	CacheHandler: Storing XML for http://www.goodreads.com/search.xml?q=between+the+scenes&key=ckvsiSDsuqh7omh74ZZ6Q
2016-07-06 17:19:40	DEBUG	Searching for between the scenes at: http://www.goodreads.com/search.xml?q=between+the+scenes&key=ckvsiSDsuqh7omh74ZZ6Q
2016-07-06 17:19:40	DEBUG	Now searching GoodReads API with keyword: between the scenes
2016-07-06 17:19:19	INFO	Log cleared, level set to [2]- Log Directory is []
```

**Comment by philborman** [comment]
Silly typo, should be AuthorID
Just pushed a fix for this.

**Comment by perezbalen** [comment]
Still geting error after update:

```

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Applications/LazyLibrarian/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/Applications/LazyLibrarian/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Applications/LazyLibrarian/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Applications/LazyLibrarian/lazylibrarian/webServe.py", line 729, in addBook
    if AuthorID:
UnboundLocalError: local variable 'AuthorID' referenced before assignment

```



Branch: master Current Version: ea2ed39b252e0f6f2f9a0bbbc6930a1ceb775e78 : 
Latest Version: ea2ed39b252e0f6f2f9a0bbbc6930a1ceb775e78

**Comment by philborman** [comment]
Ah, sorry about that. Earlier reference to AuthorName needed changing to AuthorID.
I stopped using AuthorName because of problems with accents and unicode and AuthorID should be safe. Added a couple of books here and it all works properly now.

**Comment by perezbalen** [comment]
Seems to be working now. Thanks.
