### ISSUE TITLE
UnboundLocalError booksub

### ISSUE THREAD

**Issue by daktak** [DobyTang/LazyLibrarian#439]
Adding a book from the search gives the following error

Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/lazylibrarian/lazylibrarian/gr.py", line 682, in find_book
    booksub = replace_all(booksub, dic)
UnboundLocalError: local variable 'booksub' referenced before assignment

**Comment by forge33** [comment]
Hi Datak,
what book where you trying to add?

**Comment by daktak** [comment]
David Heinemeier Hansson, Jason Fried - Remote: Office Not Required LL.(17316682)

**Comment by philborman** [comment]
Ah, silly error. Took out an "else" clause that I thought was redundant, but it's not. 
Fixed now.
