### ISSUE TITLE
Error when Author name includes quotation marks

### ISSUE THREAD

**Issue by lavaguy1** [DobyTang/LazyLibrarian#455]
Hi, 
I'm getting an error when trying to add the author E. E. "Doc" Smith to my library... 

Error looks like this:

```
Exception in thread REFRESHAUTHOR:
Traceback (most recent call last):
 File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner self.run()
 File "/usr/lib/python2.7/threading.py", line 763 in run self.__target(*self.__args, **self.__kwargs)
 File "/opt/LazyLibrarian/lazylibrarian/importer.py", line 62, in addAuthorToDB GR.get_author_books(authorid, authorname, refresh=refresh)
 File "/opt/LazyLibrarian/lazylibrarian/gr.py", line 460, in get_author_books (bookname, authorNameResult))
 File "/opt/LazyLibrarian/lazylibrarian/database.py", line 64, in select sqlResults = self.action(query, args).fetchall()
 File "/opt/LazyLibrarian/lazylibrarian/database.py", line 41, in action sqlResult = self.connection.execute(query)
OperationalError: near "Doc": syntax error

```
using version:

Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 735face6806dabfae4bd1c1655218a495c840a6b : Latest Version: 735face6806dabfae4bd1c1655218a495c840a6b

Thanks for maintaining and improving this great program!

**Comment by philborman** [comment]
Think this should be fixed now, hope I've found all the places that needed patching to allow quotemarks. Please close the issue if you agree :-)  
A warning though - This particular author is hard to search for, as many of his books have very similar names. You might need to watch the match % values closely so you don't grab the wrong book!

**Comment by lavaguy1** [comment]
Wow! that was quick! I'll give it a try!

Thanks!

**Comment by lavaguy1** [comment]
Seems to be working! Thanks again for the quick response!
