### ISSUE TITLE
Adding new authors status loading never finds books 

### ISSUE THREAD

**Issue by jestes** [DobyTang/LazyLibrarian#509]
This is the error if you select the author 

404 Not Found

The path '/None' was not found.

Traceback (most recent call last):
  File "/volume1/@appstore/lazylibrarian/share/LazyLibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/volume1/@appstore/lazylibrarian/share/LazyLibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/lazylibrarian/share/LazyLibrarian/cherrypy/_cperror.py", line 411, in __call__
    raise self
NotFound: (404, "The path '/None' was not found.")
Powered by CherryPy 3.6.0

**Comment by philborman** [comment]
Anything in the log just before the cherrypy line, ie which lazylibrarian page called cherrypy

**Comment by jestes** [comment]
Did not see anything.  Just started working again
