### ISSUE TITLE
Ignore Author issue

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#528]
I'm getting the following when clicking Ignore Author from the Author page: 

Traceback (most recent call last):
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/webServe.py", line 593, in ignoreAuthor
    AuthorName = authorsearch[0]['AuthorName']
TypeError: string indices must be integers

I've tried it with a couple of different authors.

Thanks :)

**Comment by philborman** [comment]
Yep, that's a bug. I changed some of the database functions that only expect one result, and missed that one. Will push a fix shortly

**Comment by DarkSir23** [comment]
Awesome, thanks,
