### ISSUE TITLE
File permissions revisited

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#544]
Could the same file permissions (644) be done on torrent and nzb files being added to blackholes?

**Comment by DarkSir23** [comment]
Nevermind, it already is.  Something else isn't working.  Ignore me.

**Comment by philborman** [comment]
Actually I think it's not working. Magnets and nzb aren't always set,
torrents are.
Fixed in next release.

**Comment by DarkSir23** [comment]
Not sure if this is related, but after the newest update, I'm getting this on torrent blackhole saves:

```
20-Dec-2016 20:27:22 - ERROR   :: SEARCHRSS : Unhandled exception in search_rss_book: Traceback (most recent call last):
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/searchrss.py", line 83, in search_rss_book
    found = processResultList(resultlist, authorname, bookname, book, 'book')
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/searchrss.py", line 213, in processResultList
    newValueDict["NZBtitle"], tor_url)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/searchtorrents.py", line 369, in TORDownloadMethod
    tor_path = os.path.join(lazylibrarian.TORRENT_DIR, tor_name)
  File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

```

**Comment by philborman** [comment]
Looks like a separate issue,  seems the torrent doesn't supply a name. I will trap this in the next release too.

**Comment by philborman** [comment]
Yep, logfiles was broken too, kept reverting to 10.
Fixed now (I think)

**Comment by DarkSir23** [comment]
Looks good so far :)
