### ISSUE TITLE
On philborman fork, simplejson issue preventing startup

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#583]
I'm getting the following:

Traceback (most recent call last):
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/LazyLibrarian.py", line 12, in <module>
    import lazylibrarian
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/__init__.py", line 29, in <module>
    from lazylibrarian import logger, postprocess, searchnzb, searchtorrents, searchrss, \
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 34, in <module>
    from lazylibrarian.notifiers import notify_download
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/notifiers/__init__.py", line 23, in <module>
    import pushbullet
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/notifiers/pushbullet.py", line 25, in <module>
    from pushbullet2 import PushBullet
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/notifiers/pushbullet2.py", line 15, in <module>
    import lib.simplejson as json
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lib/simplejson/__init__.py", line 113, in <module>
    from .encoder import JSONEncoder, JSONEncoderForHTML, RawJSON
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lib/simplejson/encoder.py", line 17, in <module>
    from simplejson.decoder import PosInf
ImportError: No module named simplejson.decoder

If I comment out the import line, it loads fine, but I thought you might want to know.  :)

**Comment by philborman** [comment]
Yes,  I'm upgrading the simplejson library and others trying to get it to
build under python 3
The line should just say decoder, not simplejson. decoder
