### ISSUE TITLE
db_needs_upgrade IndexError: list index out of range

### ISSUE THREAD

**Issue by bcg62** [DobyTang/LazyLibrarian#592]
I just updated and am now getting this when trying to access the instance. Anyone know what this is?

```
Traceback (most recent call last):
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/webServe.py", line 70, in index
    if lazylibrarian.db_needs_upgrade():
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/__init__.py", line 1513, in db_needs_upgrade
    db_version = result[0]
IndexError: list index out of range
```

**Comment by bcg62** [comment]
Nevermind, restarting my jail seems to have fixed it
