### ISSUE TITLE
Running latest philborman build:

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#624]
Getting this opening Magazines:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.
`
Traceback (most recent call last):
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/webServe.py", line 1168, in magazines
    if not os.path.isfile(magimg):
  File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
`

FreeNAS, version 3f1c0b7b98d906d4f6389222c0973f38b4bacb3a

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by philborman** [comment]
Yep, bug. Fixed now.  For ease of tracking, can you put any future issues with my build on my github page rather than dobytang,  I tend to break mine quite regularly as I develop on one machine and test on a second one, with my git as the link between the two. Lots of the issues you might hit while using my build are knocked out before I ship it to DobyTang.  Thanks.

**Comment by DarkSir23** [comment]
I tried at one point.  I actually didn't see a place to report issues.  But I'll take a look again :)

**Comment by philborman** [comment]
Yes, you're right. That's strange, wonder why. I will try and get it sorted.
