### ISSUE TITLE
Error while adding author

### ISSUE THREAD

**Issue by djdmd** [DobyTang/LazyLibrarian#678]
T
### Relevant debug log with api keys and any passwords redacted

When adding a new author , i have this errror in logs :

> 2017-03-06 21:43:38	INFO	[Veronica Roth] Book processing complete: Added 5 books to the database
2017-03-06 21:36:15	ERROR	Unhandled exception in AuthorUpdate: Traceback (most recent call last): File "/opt/lazylibrarian/lazylibrarian/common.py", line 203, in authorUpdate diff = datecompare(dtnow.strftime("%Y-%m-%d"), author['DateAdded']) TypeError: list indices must be integers, not str
2017-03-06 20:36:15	ERROR	Unhandled exception in AuthorUpdate: Traceback (most recent call last): File "/opt/lazylibrarian/lazylibrarian/common.py", line 203, in authorUpdate diff = datecompare(dtnow.strftime("%Y-%m-%d"), author['DateAdded']) TypeError: list indices must be integers, not str
2017-03-06 19:40:57	INFO	Search for magazines complete

**Comment by philborman** [comment]
Looks like the author update task is trying to run while an author is loading, and not liking the "DateAdded" value for the author that is loading. I will need to add something that says "ignore loading authors" as the date isn't set until loading is complete. Thanks for the bug report.

**Comment by philborman** [comment]
Should be fixed in latest release, could you, let me know if it is working for you now. Thanks.
