### ISSUE TITLE
Error upgrading database from v14 to v15.

### ISSUE THREAD

**Issue by wizzy99** [DobyTang/LazyLibrarian#681]
Current Version: 8d9b1dac3eed17557080080b81531499d0334f82
Updated via git
fedora 25

I updated this morning to the latest version from within LL and see the following in the log:

2017-03-10 11:22:16	ERROR	Unhandled exception in database update: Traceback (most recent call last): File "/home/user/LazyLibrarian/lazylibrarian/dbupgrade.py", line 548, in dbupgrade setSeries(seriesdict, book['BookID']) File "/home/user/LazyLibrarian/lazylibrarian/bookwork.py", line 104, in setSeries (item, book['AuthorID'])) File "/home/user/LazyLibrarian/lazylibrarian/database.py", line 46, in action sqlResult = self.connection.execute(query) OperationalError: near "Jack": syntax error
2017-03-10 11:22:16	ERROR	Database error: near "Jack": syntax error
2017-03-10 11:22:16	ERROR	Database error: near "Jack": syntax error
2017-03-10 11:07:46	INFO	Updating book series for 1234 books
2017-03-10 11:07:46	INFO	Updating database to version 15, current version is 14

From the debug log:
10-Mar-2017 11:22:16 - DEBUG   :: DB_UPGRADE : getBookWork: Caching workpage for /home/user/LazyLibrarian/cache/WorkCache/26026197.html
10-Mar-2017 11:22:16 - DEBUG   :: DB_UPGRADE : getBookWork: Librarything error: [No work found.] for Blake Crouch Crimespree Magazine #1 and 2
10-Mar-2017 11:22:16 - DEBUG   :: DB_UPGRADE : getBookWork: Caching workpage for /home/user/LazyLibrarian/cache/WorkCache/12303305.html
10-Mar-2017 11:22:16 - DEBUG   :: DB_UPGRADE : getBookWork: Returning Cached entry for 854145 Series
10-Mar-2017 11:22:16 - DEBUG   :: DB_UPGRADE : getBookWork: Returning Cached entry for 18838050 Series
10-Mar-2017 11:22:16 - DEBUG   :: DB_UPGRADE : getBookWork: Returning Cached entry for 11483093 Series
10-Mar-2017 11:22:16 - ERROR   :: DB_UPGRADE : Database error: near "Jack": syntax error
10-Mar-2017 11:22:16 - ERROR   :: DB_UPGRADE : Database error: near "Jack": syntax error
10-Mar-2017 11:22:16 - ERROR   :: DB_UPGRADE : Unhandled exception in database update: Traceback (most recent call last):
  File "/home/user/LazyLibrarian/lazylibrarian/dbupgrade.py", line 548, in dbupgrade
    setSeries(seriesdict, book['BookID'])
  File "/home/user/LazyLibrarian/lazylibrarian/bookwork.py", line 104, in setSeries
    (item, book['AuthorID']))
  File "/home/user/LazyLibrarian/lazylibrarian/database.py", line 46, in action
    sqlResult = self.connection.execute(query)
OperationalError: near "Jack": syntax error

**Comment by philborman** [comment]
Bug is fixed, just not pushed to master branch yet. Will push it in a few
hours, just testing a bit more
