### ISSUE TITLE
Error during post-processing

### ISSUE THREAD

**Issue by ATor69** [DobyTang/LazyLibrarian#687]
Current Version: 536c271edfce36bec945e7120075ca836aa90fa7

OS: Debian Jessie

Interface: Bootstrap

Install: GIT

2017-03-11 12:15:49	ERROR	Unhandled exception in processDir: Traceback (most recent call last): File "/home/username/LazyLibrarian/lazylibrarian/postprocess.py", line 430, in processDir processExtras(myDB, dest_path, global_name, data) File "/home/username/LazyLibrarian/lazylibrarian/postprocess.py", line 782, in processExtras newValueDict = {"HaveBooks": havebooks['counter']} TypeError: list indices must be integers, not str

2017-03-11 12:15:49	ERROR	Failed query: [SELECT count("BookID") as counter FROM books WHERE AuthorName="D.K. Holmberg" AND (Status="Have" OR Status="Open")]

2017-03-11 12:15:49	ERROR	Database error: no such column: AuthorName

This was after an update from v15 to v16 Database, total update 20 commits

**Comment by ATor69** [comment]
Appears to be corrected, closing
