### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by hctancredi** [DobyTang/LazyLibrarian#713]
I recently noticed that all my books were not appearing and I'm getting all these errors when trying to refresh it.

Current Version: d5c2771a97b36db01708c9e5bebaefb5db927c8e 
S.O: Unraid Docker
Interface: bookstrap

2017-03-26 15:05:05	ERROR	Unhandled exception in GR.get_author_books: Traceback (most recent call last): File "/app/lazylibrarian/lazylibrarian/gr.py", line 571, in get_author_books setSeries(seriesdict, bookid) File "/app/lazylibrarian/lazylibrarian/bookwork.py", line 125, in setSeries (match['SeriesID'], book['AuthorID'])) File "/app/lazylibrarian/lazylibrarian/database.py", line 46, in action sqlResult = self.connection.execute(query) OperationalError: no such table: seriesauthors
2017-03-26 15:05:05	ERROR	Failed query: [Insert into seriesauthors ("SeriesID", "AuthorID") VALUES ("55", "4369922")]
2017-03-26 15:05:05	ERROR	Database error: no such table: seriesauthors
2017-03-26 15:05:05	ERROR	Failed query: [SELECT SeriesID from seriesauthors WHERE SeriesID="55" and AuthorID="4369922"]
2017-03-26 15:05:05	ERROR	Database error: no such table: seriesauthors
2017-03-26 15:05:04	ERROR	Failed query: [SELECT AuthorName,BookName FROM books,authors WHERE authors.AuthorID = books.AuthorID AND BookID=9359818]
2017-03-26 15:05:04	ERROR	Database error: ambiguous column name: AuthorName
2017-03-26 15:05:04	ERROR	Failed query: [SELECT BookID FROM books,authors WHERE books.AuthorID = authors.AuthorID and BookName = "God's War" and AuthorName = "Kameron Hurley" COLLATE NOCASE]
2017-03-26 15:05:04	ERROR	Database error: ambiguous column name: AuthorName

**Comment by philborman** [comment]
Looks like the database is out of sync with the software. The latest database version is 17, which includes a seriesauthors table and removes authorname from the book table (which is why you are getting the ambiguous column name)

Can't see how the software manages to get this far without running the database upgrade routine. Lazylibrarian checks the database version when it starts up, and upgrades the database if needed.
Can you check the database version you are running - lazylibrarian prints this in the log at startup. Did you notice a database upgrade happening when you last upgraded lazylibrarian? At the moment I'm wondering if it's docker related somehow, as the git and zip source both work as expected.

**Comment by hctancredi** [comment]
Seems like that I had version 15 and the upgrade to version 17 was not working. 

Searching past issues, I ended up removing the database file and manually imported everything back. 
I couldn't even save my wanted list, so I decided to go for a hard reset.

After that, the upgrade worked and everything seems to be ok for now.

Do you still want to see the logs? Maybe there's something to dig into.

Thanks anyway.

**Comment by philborman** [comment]
Anything in the logs to show why the upgrade failed? It's a fairly simple change, just a few sqlite commands that shuffle data around.

**Comment by fastrack20** [comment]
I ran into the same issue. This is what I see in the log:

21-Mar-2017 11:10:57 - DEBUG   :: DB_UPGRADE : Database integrity check: ok
21-Mar-2017 11:10:57 - INFO    :: DB_UPGRADE : Updating database to version 17, current version is 13
21-Mar-2017 11:10:57 - DEBUG   :: DB_UPGRADE : Moving 618 author images to new location
21-Mar-2017 11:12:32 - DEBUG   :: DB_UPGRADE : Author Image cache updated
21-Mar-2017 11:12:32 - DEBUG   :: DB_UPGRADE : Moving 34837 book images to new location
21-Mar-2017 12:50:00 - DEBUG   :: DB_UPGRADE : Book Image cache updated
21-Mar-2017 12:50:08 - DEBUG   :: DB_UPGRADE : Updating book series for 38747 books
21-Mar-2017 12:50:09 - DEBUG   :: DB_UPGRADE : getBookWork: Returning Cached entry for 8855321 Series
21-Mar-2017 12:50:10 - ERROR   :: DB_UPGRADE : Database error: no such table: seriesauthors
21-Mar-2017 12:50:10 - ERROR   :: DB_UPGRADE : Failed query: [SELECT SeriesID from seriesauthors WHERE SeriesID="1" and AuthorID="4192148"]
21-Mar-2017 12:50:10 - ERROR   :: DB_UPGRADE : Database error: no such table: seriesauthors
21-Mar-2017 12:50:10 - ERROR   :: DB_UPGRADE : Failed query: [Insert into seriesauthors ("SeriesID", "AuthorID") VALUES ("1", "4192148")]
21-Mar-2017 12:50:10 - ERROR   :: DB_UPGRADE : Unhandled exception in database update: Traceback (most recent call last):
  File "D:\LazyLibrarian\lazylibrarian\dbupgrade.py", line 551, in dbupgrade
    setSeries(seriesdict, book['BookID'])
  File "D:\LazyLibrarian\lazylibrarian\bookwork.py", line 118, in setSeries
    (match['SeriesID'], book['AuthorID']))
  File "D:\LazyLibrarian\lazylibrarian\database.py", line 46, in action
    sqlResult = self.connection.execute(query)
OperationalError: no such table: seriesauthors

**Comment by philborman** [comment]
That's found it, thank you.
One of the functions used in upgrading the database is trying to add data into a table that doesn't exist yet. Doesn't happen on new databases, and doesn't happen if you are not too far behind when upgrading. Easy to fix, will post a new version in a couple of hours.

**Comment by fastrack20** [comment]
I just updated and that seems to have corrected the issue.
