### ISSUE TITLE
Error adding an author from goodreads

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#740]
Current Version: 6918a5c89a2cdb97bf1c679aff7fbd025df683c4 : Latest Version: 6918a5c89a2cdb97bf1c679aff7fbd025df683c4

mac osx

bookstrap

goodreads

git install

DebugLog:

2017-04-22 22:25:36	DEBUG	[Pierce Brown] Author update complete
2017-04-22 22:25:36	ERROR	Unhandled exception in GR.get_author_books: Traceback (most recent call last): File "/LazyLibrarian/lazylibrarian/gr.py", line 573, in get_author_books setSeries(seriesdict, bookid) File "/LazyLibrarian/lazylibrarian/bookwork.py", line 183, in setSeries newseries = "%s %s" % (item['SeriesName'], item['SeriesNum']) TypeError: string indices must be integers
2017-04-22 22:25:36	DEBUG	Unique entry suppressed [INSERT INTO seriesauthors ("SeriesID", "AuthorID") VALUES ("726", "6474348")]
2017-04-22 22:25:36	DEBUG	Updated series: 15839976 [{u'The Red Rising Trilogy': u'1'}]

**Comment by philborman** [comment]
This was fixed in latest version yesterday. An upgrade should sort it out.
