### ISSUE TITLE
Error 500 on magazine multiple selection ignore.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#741]
When selecting multiple magazines in past issues, and then clicking ignore; I get a 500 error.

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
Traceback (most recent call last):
  File "Z:\Applications\lazylibrarian\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "Z:\Applications\lazylibrarian\cherrypy\lib\encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "Z:\Applications\lazylibrarian\cherrypy\_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "Z:\Applications\lazylibrarian\lazylibrarian\webServe.py", line 1370, in markPastIssues
    myDB.action('UPDATE pastissues set status=%s WHERE NZBurl="%s"' % (action, nzburl))
  File "Z:\Applications\lazylibrarian\lazylibrarian\database.py", line 46, in action
    sqlResult = self.connection.execute(query)
OperationalError: no such column: Ignored

**Comment by philborman** [comment]
Missing quotes around the status="%s"
Will push a fix later today.

**Comment by MrMxyzptlk** [comment]
Excellent!
