### ISSUE TITLE
Database Integrity error: columns SeriesID, AuthorID are not unique

### ISSUE THREAD

**Issue by norrlandskatten** [DobyTang/LazyLibrarian#748]
Trouble adding new authors. The problem seem to present it self when adding a new author with a book series. 

Adding a new author made all other authors with series to get stuck in status Loading while authors without series are is status active.

To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 5e224074035a997e57ff4933f021df4eafa14cee : Latest Version: 5e224074035a997e57ff4933f021df4eafa14cee

### Operating system used (windows, mac, linux, NAS type)
CentOS 7 - 3.10.0-514.10.2.el7.x86_64

### Interface in use (default, bookstrap)
Default

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
GIT

### Relevant debug log with api keys and any passwords redacted
2017-04-25 18:40:32	ERROR	Unhandled exception in GR.get_author_books: Traceback (most recent call last): File "/opt/lazylibrarian/lazylibrarian/gr.py", line 573, in get_author_books setSeries(seriesdict, bookid) File "/opt/lazylibrarian/lazylibrarian/bookwork.py", line 177, in setSeries (match['SeriesID'], book['AuthorID']), suppress='UNIQUE') File "/opt/lazylibrarian/lazylibrarian/database.py", line 46, in action sqlResult = self.connection.execute(query) IntegrityError: columns SeriesID, AuthorID are not unique
2017-04-25 18:40:32	ERROR	Failed query: [INSERT INTO seriesauthors ("SeriesID", "AuthorID") VALUES ("240", "104756")]
2017-04-25 18:40:32	ERROR	Database Integrity error: columns SeriesID, AuthorID are not unique

**Comment by philborman** [comment]
There is some code to catch unique constraints that isn't working here. You
are getting a different error message back from sqlite than we are
expecting. The error I get here starts with "UNIQUE constraint failed". I
will add some code to trap "are not unique" as well. We only want one
database entry per series/author combination, in case an author has
contributed more than one book to a series, and it should be quicker to
(try and add / catch the error) than (check if already there and if not add
it) which would take two database calls instead of one.
Will push a fix in an hour or two.

You will need to upgrade, then refresh each author marked as "loading"

**Comment by norrlandskatten** [comment]
Updated to latest version, refreshed authors, works like a charm. Thank you!
