### ISSUE TITLE
new libgen parser errors?

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#781]
I didn't get any of these errors before the latest update, now I have a lot.
Here is a small segment of the logs:

2017-05-12 06:33:21	INFO	Nearest NZB match (72%): Churchill Winston S The Birth of Britain A History of the English Speaking Peoples Volume mobi using book search for Winston S Churchill Lord Randolph Churchill Volume II
2017-05-12 06:33:03	ERROR	An error occurred in the libgen parser: 'ascii' codec can't encode character u'\xf8' in position 4: ordinal not in range(128)
2017-05-12 06:33:02	INFO	NZB Searches for Winston S. Churchill The Art of Diplomacy: Winston Churchill and the Pursuit of Painting returned no results.
2017-05-12 06:32:52	INFO	Nearest NZB match (66%): Churchill Winston S The Birth of Britain A History of the English Speaking Peoples Volume mobi using book search for Winston S Churchill The Art of Diplomacy
2017-05-12 06:32:39	ERROR	An error occurred in the libgen parser: 'ascii' codec can't encode character u'\xf8' in position 4: ordinal not in range(128)
2017-05-12 06:32:32	INFO	NZB Searches for Winston S. Churchill Lord Randolph Churchill Vol. 1 returned no results.
2017-05-12 06:32:24	INFO	Nearest NZB match (71%): Churchill Winston Grand Alliance using book search for Winston S Churchill Lord Randolph Churchill Vol 1
2017-05-12 06:32:09	ERROR	An error occurred in the libgen parser: 'ascii' codec can't encode characters in position 5-8: ordinal not in range(128)

**Comment by philborman** [comment]
Nothing has changed in the libgen parser for a while, I guess the problem a support routine somewhere but the debug message doesn't give enough info. Will push a more verbose version.

**Comment by MrMxyzptlk** [comment]
Now unfortunately, no matter what I search for this is what i get.

2017-05-12 09:04:21	ERROR	An error occurred in the libgen parser: 'ascii' codec can't encode character u'\xf8' in position 4: ordinal not in range(128)
2017-05-12 09:04:14	ERROR	An error occurred in the libgen parser: 'ascii' codec can't encode character u'\xf8' in position 4: ordinal not in range(128)
2017-05-12 09:04:07	ERROR	An error occurred in the libgen parser: 'ascii' codec can't encode characters in position 5-8: ordinal not in range(128)
2017-05-12 09:03:49	ERROR	An error occurred in the libgen parser: 'ascii' codec can't encode character u'\xe2' in position 4: ordinal not in range(128)
2017-05-12 09:03:41	ERROR	An error occurred in the libgen parser: 'ascii' codec can't encode characters in position 13-14: ordinal not in range(128)
2017-05-12 09:01:35	INFO	Searching for 1 magazine

**Comment by philborman** [comment]
If you upgrade to latest and turn debug on you should get more info (hopefully)

**Comment by MrMxyzptlk** [comment]
OK, I just did a magazine search with debug logging on. It appears to search and find and send to downloader successfully, but as soon the search is complete, that is where the errors begin?

2017-05-12 09:11:41	DEBUG	libgen: Traceback (most recent call last): File "Z:\Applications\lazylibrarian\lazylibrarian\torrentparser.py", line 569, in GEN new_soup = BeautifulSoup(bookresult) File "Z:\Applications\lazylibrarian\lib\BeautifulSoup.py", line 1522, in __init__ BeautifulStoneSoup.__init__(self, *args, **kwargs) File "Z:\Applications\lazylibrarian\lib\BeautifulSoup.py", line 1147, in __init__ self._feed(isHTML=isHTML) File "Z:\Applications\lazylibrarian\lib\BeautifulSoup.py", line 1189, in _feed SGMLParser.feed(self, markup) File "C:\Python27\lib\sgmllib.py", line 104, in feed self.goahead(0) File "C:\Python27\lib\sgmllib.py", line 143, in goahead k = self.parse_endtag(i) File "C:\Python27\lib\sgmllib.py", line 320, in parse_endtag self.finish_endtag(tag) File "C:\Python27\lib\sgmllib.py", line 358, in finish_endtag method = getattr(self, 'end_' + tag) UnicodeEncodeError: 'ascii' codec can't encode character u'\xe2' in position 4: ordinal not in range(128)
2017-05-12 09:11:41	ERROR	An error occurred in the libgen parser: 'ascii' codec can't encode character u'\xe2' in position 4: ordinal not in range(128)
2017-05-12 09:11:39	INFO	Search for magazines complete

**Comment by MrMxyzptlk** [comment]
This error just popped up:

2017-05-12 09:16:44	DEBUG	libgen: Traceback (most recent call last): File "Z:\Applications\lazylibrarian\lazylibrarian\torrentparser.py", line 569, in GEN new_soup = BeautifulSoup(bookresult) File "Z:\Applications\lazylibrarian\lib\BeautifulSoup.py", line 1522, in __init__ BeautifulStoneSoup.__init__(self, *args, **kwargs) File "Z:\Applications\lazylibrarian\lib\BeautifulSoup.py", line 1147, in __init__ self._feed(isHTML=isHTML) File "Z:\Applications\lazylibrarian\lib\BeautifulSoup.py", line 1189, in _feed SGMLParser.feed(self, markup) File "C:\Python27\lib\sgmllib.py", line 104, in feed self.goahead(0) File "C:\Python27\lib\sgmllib.py", line 143, in goahead k = self.parse_endtag(i) File "C:\Python27\lib\sgmllib.py", line 320, in parse_endtag self.finish_endtag(tag) File "C:\Python27\lib\sgmllib.py", line 358, in finish_endtag method = getattr(self, 'end_' + tag) UnicodeEncodeError: 'ascii' codec can't encode characters in position 8-9: ordinal not in range(128)
2017-05-12 09:16:44	ERROR	An error occurred in the libgen parser: 'ascii' codec can't encode characters in position 8-9: ordinal not in range(128)

**Comment by philborman** [comment]
Looks like libgen have changed their html and removed a link, will need a
bit of work...

**Comment by philborman** [comment]
Seems sorted now, will push a new version later today
