### ISSUE TITLE
Cannot access magazines anymore

### ISSUE THREAD

**Issue by deurk** [DobyTang/LazyLibrarian#799]
### Source of LazyLibrarian installation Git

Clicking on the Magazine link in the menu gives this error message:

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/lazylibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/lazylibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/lazylibrarian/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/lazylibrarian/lazylibrarian/webServe.py", line 1147, in magazines
    if not lazylibrarian.CONFIG['TOGGLE'] and not lazylibrarian.CONFIG['MAG_IMG']:
KeyError: 'TOGGLE'
Powered by CherryPy 3.6.0

```

**Comment by peddlerguy** [comment]
I was going to post the same thing - was working fine last night, then I saw that I was 6 commits behind so I updated, and that's when the error started - everything else appears to be ok

**Comment by philborman** [comment]
Yes, theres a typo, should be TOGGLES not TOGGLE
Sorry about that, just pushed a fix
