### ISSUE TITLE
Error after Author/ library Scan

### ISSUE THREAD

**Issue by Black-girl101** [DobyTang/LazyLibrarian#811]
To help with identifying and fixing issues, please include as much information as possible, including:
**LazyLibrarian version number**
Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 90cb03b5513a75e71b9bdec037381ed232550391 : Latest Version: 90cb03b5513a75e71b9bdec037381ed232550391
**Operating system used:** Mac
 **Which api** Goodreads
**Source of your LazyLibrarian installation** git

**Debug Log:** 
2017-05-29 08:09:49	ERROR	Unhandled exception in libraryScan: Traceback (most recent call last): File "/Applications/LazyLibrarian/lazylibrarian/librarysync.py", line 633, in LibraryScan copyfile(coverimg, cacheimg) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile with open(dst, 'wb') as fdst: IOError: [Errno 2] No such file or directory: u'/Applications/LazyLibrarian/cache/book/24516340.jpg'
2017-05-29 08:09:49	DEBUG	Exact match [Remember When]
2017-05-29 08:09:49	DEBUG	Stripped authorname [A. D. Ryan] to [A.D. Ryan]
2017-05-29 08:09:49	DEBUG	file meta [] [eng] [A. D. Ryan] [Remember When] []
2017-05-29 08:09:49	DEBUG	book meta [] [en] [A. D. Ryan] [Remember When] [epub]
2017-05-29 08:09:49	DEBUG	[/Volumes/Books,Music,Programs/Books] Now scanning subdirectory /A. D. Ryan/Remember When (1519)
2017-05-29 08:09:49	INFO	Scanning ebook directory: /Volumes/Books,Music,Programs/Books
2017-05-29 08:09:45	INFO	Log cleared, level set to [2]- Log Directory is [/Applications/LazyLibrarian/Logs]

**Comment by philborman** [comment]
This is a copy of #809 
The directories are not getting created properly. Creating the "book" and "author" folders manually will fix it for now, a fix will be out in a few days as I'm away for a while.  You need to create...
/Applications/LazyLibrarian/cache/book/
/Applications/LazyLibrarian/cache/author/
