### ISSUE TITLE
500 Internal Server Error while manually searching author/title

### ISSUE THREAD

**Issue by adamgoldberg** [DobyTang/LazyLibrarian#820]
```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/root/LazyLibrarian/LazyLibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/root/LazyLibrarian/LazyLibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/root/LazyLibrarian/LazyLibrarian/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/root/LazyLibrarian/LazyLibrarian/lazylibrarian/webServe.py", line 576, in booksearch
    results = searchItem(searchterm, bookid)
  File "/root/LazyLibrarian/LazyLibrarian/lazylibrarian/manualbook.py", line 51, in searchItem
    resultlist, nproviders = IterateOverTorrentSites(book, 'general')
  File "/root/LazyLibrarian/LazyLibrarian/lazylibrarian/providers.py", line 262, in IterateOverTorrentSites
    BlockProvider(prov, error)
  File "/root/LazyLibrarian/LazyLibrarian/lazylibrarian/providers.py", line 199, in BlockProvider
    newentry = {"name": who, "resume": timenow + check_int(lazylibrarian.BLOCKLIST_TIMER, 3600), "reason": why}
AttributeError: 'module' object has no attribute 'BLOCKLIST_TIMER'
Powered by CherryPy 3.6.0
```

**Comment by philborman** [comment]
Thanks, that was a typo. Should be fixed now.
