### ISSUE TITLE
Update failed and gui is unavailable

### ISSUE THREAD

**Issue by rv10guy** [DobyTang/LazyLibrarian#826]
I attempted to update through the GUI. It indicated there were 21 commits to apply. The update waited 30 seconds and then during the refresh the gui timed out. I manually stopped and started LazyLibrarian and can't get a gui interface. I stopped the service and tried update from the command line and get the following message..

03-Jun-2017 19:12:41 - INFO :: MAIN : Log level set to [2]- Log Directory is [/opt/lazylibrarian/Logs] - Config level is [2]
03-Jun-2017 19:12:41 - INFO :: MAIN : Screen Log set to INFO/WARN/ERROR
03-Jun-2017 19:12:41 - DEBUG :: MAIN : General : destination_dir ->
03-Jun-2017 19:12:41 - DEBUG :: MAIN : Newznab0 : enabled -> False
03-Jun-2017 19:12:41 - DEBUG :: MAIN : Newznab0 : host ->
03-Jun-2017 19:12:41 - DEBUG :: MAIN : Newznab0 : api ->
03-Jun-2017 19:12:41 - DEBUG :: MAIN : Newznab0 : generalsearch -> search
03-Jun-2017 19:12:41 - DEBUG :: MAIN : Newznab0 : booksearch -> book
03-Jun-2017 19:12:41 - DEBUG :: MAIN : Newznab0 : magsearch ->
Traceback (most recent call last):
  File "./LazyLibrarian.py", line 225, in <module>
    main()
  File "./LazyLibrarian.py", line 139, in main
    lazylibrarian.initialize()
  File "/opt/lazylibrarian/lazylibrarian/__init__.py", line 437, in initialize
    config_read()
  File "/opt/lazylibrarian/lazylibrarian/__init__.py", line 530, in config_read
    "AUDIOSEARCH": check_setting('str', newz_name, 'audiosearch', ''),
  File "/opt/lazylibrarian/lazylibrarian/__init__.py", line 378, in check_setting
    except ConfigParser.Error:
NameError: global name 'ConfigParser' is not defined

To help with identifying and fixing issues, please include as much information as possible, including:

**Comment by rv10guy** [comment]
Closing issue. Previously reported issue #825.
