### ISSUE TITLE
libgen parsing issue

### ISSUE THREAD

**Issue by AndyHazz** [DobyTang/LazyLibrarian#906]
The libgen provider has stopped working for me - I had it working fine not long ago.
I use an an ip address for libgen instead of domain name (the domain is blocked for me). I can still access libgen via ip in a web browser so it should work from LL ...

The relevant bit of my config.ini:

```
[GEN]
gen = 1
gen_host = 93.174.95.27
gen_dlpriority = 0
gen_search = search.php
gen2_dlpriority = 10
gen2_host = 93.174.95.27
gen2 = 1
gen2_search = foreignfiction/index.php
```

Here a debug log - it seems to get the search results ok (apart from tripping up on a character encoding issue?), but then when it comes to getting the link URLs it malforms them as e.g. `http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=e0545...`:

```
10-Jul-2017 22:12:16 - DEBUG   :: WEBSERVER : [IterateOverDirectSites] - 93.174.95.27 search.php
10-Jul-2017 22:12:17 - DEBUG   :: WEBSERVER : Parsing results from <a href="http://93.174.95.27/search.php?column=def&res=100&req=H.G+Wells+The+War+of+the+Worlds&phrase=0&open=0&view=simple">libgen</a>
10-Jul-2017 22:12:18 - DEBUG   :: WEBSERVER : Stripped authorname [H. G. Wells] to [H.G. Wells]
10-Jul-2017 22:12:22 - DEBUG   :: POSTPROCESS : Checking 76 files in /storage/nfs/volume1/downloads/completed/ebooks
10-Jul-2017 22:12:22 - DEBUG   :: POSTPROCESS : Found 0 files marked "Snatched"
10-Jul-2017 22:12:22 - INFO    :: POSTPROCESS : 0 books/mags processed.
10-Jul-2017 22:12:22 - INFO    :: POSTPROCESS : Nothing marked as snatched. Stopping postprocessor.
10-Jul-2017 22:12:22 - DEBUG   :: POSTPROCESS : Stop processDir job
10-Jul-2017 22:15:22 - ERROR   :: WEBSERVER : An error occurred in the libgen parser: 'ascii' codec can't encode character u'\xfb' in position 35: ordinal not in range(128)
10-Jul-2017 22:15:22 - DEBUG   :: WEBSERVER : libgen: Traceback (most recent call last):
  File "/opt/lazylibrarian/lazylibrarian/directparser.py", line 193, in GEN
    new_soup = BeautifulSoup(bookresult)
  File "/opt/lazylibrarian/lib/BeautifulSoup.py", line 1522, in __init__
    BeautifulStoneSoup.__init__(self, *args, **kwargs)
  File "/opt/lazylibrarian/lib/BeautifulSoup.py", line 1147, in __init__
    self._feed(isHTML=isHTML)
  File "/opt/lazylibrarian/lib/BeautifulSoup.py", line 1189, in _feed
    SGMLParser.feed(self, markup)
  File "/usr/lib/python2.7/sgmllib.py", line 104, in feed
    self.goahead(0)
  File "/usr/lib/python2.7/sgmllib.py", line 143, in goahead
    k = self.parse_endtag(i)
  File "/usr/lib/python2.7/sgmllib.py", line 320, in parse_endtag
    self.finish_endtag(tag)
  File "/usr/lib/python2.7/sgmllib.py", line 358, in finish_endtag
    method = getattr(self, 'end_' + tag)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfb' in position 35: ordinal not in range(128)

10-Jul-2017 22:15:22 - DEBUG   :: WEBSERVER : Found 0 results from libgen for H.G Wells The War of the Worlds
10-Jul-2017 22:15:22 - DEBUG   :: WEBSERVER : [IterateOverDirectSites] - 93.174.95.27 foreignfiction/index.php
10-Jul-2017 22:15:32 - DEBUG   :: WEBSERVER : Parsing results from <a href="http://93.174.95.27/foreignfiction/index.php?s=H.G+Wells+The+War+of+the+Worlds&f_lang=All&f_ext=All&f_columns=0">libgen</a>
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=e0545bd04d3e4b5c12cce7589a2f1605
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Found H.G. Wells The Time Machine &amp; The War of the Worlds.mobi, Size 591872
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=f9cd8a9ad41af81df197e83a74cfb9f4
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Found H.G. Wells The Time Machine &amp; The War of the Worlds.epub, Size 453632
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=304c3a3492824633d217a8b430d650eb
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Found H.G. Wells The Time Machine and The War of the Worlds.mobi, Size 591872
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, Herbert George] to [Herbert George Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=b3b993d0277b938313ccec52bcc8a3e4
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Found Herbert George Wells The Time Machine and the War of the Worlds.epub, Size 453632
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=0e0263aa36b8925f82ea5797bd37144f
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Found H.G. Wells The War of the Worlds.epub, Size 212992
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, Herbert George] to [Herbert George Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=15db2d94365052826576074deb7db543
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Found Herbert George Wells the war of the worlds.txt, Size 428032
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=1775674b3e13ac90aa265a2ff5f9c071
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Found H.G. Wells The War of the Worlds.lit, Size 331776
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=1c95c0c35e9b20e4342a727bce393e10
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Found H.G. Wells The War of the Worlds.epub, Size 271360
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=3b3567977a0c729ee6dbddeccc53befb
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Found H.G. Wells The War of the Worlds.mobi, Size 412672
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=426b8df2cbcf1cccaa3f3719e0b02646
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Found H.G. Wells The War of the Worlds.epub, Size 327680
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=52cb04b8cb9217238d0733a78b705f5f
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Found H.G. Wells The War of the Worlds.epub, Size 202752
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=5d05dc476fd1180dfb15d55d0981d380
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Found H.G. Wells The War of the Worlds.epub, Size 1037312
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=5e0ced433d5b2bf940cd462e642ce3d5
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Found H.G. Wells The War of the Worlds.epub, Size 268288
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:34 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=670f40d05e79609230cbd7f2c99f665f
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : Found H.G. Wells The War of the Worlds.epub, Size 283648
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=6d830438cb91b85802109dd9fa0647ad
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : Found H.G. Wells The War of the Worlds.epub, Size 192512
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : http://93.174.95.27http://libgen.io/foreignfiction/ads.php?md5=86e87feb95b7d6844b321b4ede540a40
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : Error fetching link data from libgen: [Errno -2] Name or service not known
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : Found H.G. Wells The War of the Worlds.epub, Size 288768
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : Formatted authorname [Wells, H G] to [H G Wells]
10-Jul-2017 22:15:35 - DEBUG   :: WEBSERVER : Stripped authorname [H G Wells] to [H.G. Wells]
```

**Comment by philborman** [comment]
Sadly libgen keep changing their page layouts which breaks our scraper. It's getting more robust but we're not there yet, I will take a look at it tomorrow. The malformed links should be easy to fix (does it start with http, if not prefix with configured gen host). The unicode issue is a bit more of a problem as 
BeautifulSoup is set to use ascii or UTF-8 and \xfb isn't either. I'm guessing it's a russian character we can't handle. Nice full debug log though, makes it easy to reproduce the problem, which is half the battle!

**Comment by AndyHazz** [comment]
Looks like libgen maybe changed their page layout back, it just started working again with no other changes my end ...
