### ISSUE TITLE
Deleting magazines doesn't complete, leaving .opf file behind

### ISSUE THREAD

**Issue by sscraggles** [DobyTang/LazyLibrarian#935]
```
23-Jul-2017 18:30:41 - DEBUG   :: WEBSERVER : Directory /srv/booktest/_Magazines/Professional Motorsport World/2016 not deleted, not empty?
23-Jul-2017 18:30:41 - INFO    :: WEBSERVER : Issue 2016 of Professional Motorsport World deleted from disc
23-Jul-2017 18:30:41 - INFO    :: WEBSERVER : Issue 2016 of Professional Motorsport World removed from database
23-Jul-2017 18:30:41 - DEBUG   :: WEBSERVER : Directory /srv/booktest/_Magazines/Professional Motorsport World/2016-08-01 not deleted, not empty?
23-Jul-2017 18:30:41 - INFO    :: WEBSERVER : Issue 2016-08-01 of Professional Motorsport World deleted from disc
23-Jul-2017 18:30:42 - INFO    :: WEBSERVER : Issue 2016-08-01 of Professional Motorsport World removed from database
23-Jul-2017 18:30:42 - DEBUG   :: WEBSERVER : Directory /srv/booktest/_Magazines/Professional Motorsport World/2014 not deleted, not empty?
23-Jul-2017 18:30:42 - INFO    :: WEBSERVER : Issue 2014 of Professional Motorsport World deleted from disc
23-Jul-2017 18:30:42 - INFO    :: WEBSERVER : Issue 2014 of Professional Motorsport World removed from database
23-Jul-2017 18:30:42 - DEBUG   :: WEBSERVER : Directory /srv/booktest/_Magazines/Professional Motorsport World/2017-04-01 not deleted, not empty?
23-Jul-2017 18:30:42 - INFO    :: WEBSERVER : Issue 2017-04-01 of Professional Motorsport World deleted from disc
23-Jul-2017 18:30:42 - INFO    :: WEBSERVER : Issue 2017-04-01 of Professional Motorsport World removed from database

```

```
tester@macmini:~$ ls -la /srv/booktest/_Magazines/Professional\ Motorsport\ World/*/
/srv/booktest/_Magazines/Professional Motorsport World/2014/:
total 12
drwxr-xr-x 2 tester tester 4096 Jul 23 18:30 .
drwx------ 6 tester tester 4096 Jul 23 18:26 ..
-rw------- 1 tester tester  799 Jul 23 18:26 2014 - Professional Motorsport World.opf

/srv/booktest/_Magazines/Professional Motorsport World/2016/:
total 12
drwxr-xr-x 2 tester tester 4096 Jul 23 18:30 .
drwx------ 6 tester tester 4096 Jul 23 18:26 ..
-rw------- 1 tester tester  799 Jul 23 18:25 2016 - Professional Motorsport World.opf

/srv/booktest/_Magazines/Professional Motorsport World/2016-08-01/:
total 12
drwxr-xr-x 2 tester tester 4096 Jul 23 18:30 .
drwx------ 6 tester tester 4096 Jul 23 18:26 ..
-rw------- 1 tester tester  818 Jul 23 18:26 2016-08-01 - Professional Motorsport World.opf

/srv/booktest/_Magazines/Professional Motorsport World/2017-04-01/:
total 12
drwxr-xr-x 2 tester tester 4096 Jul 23 18:30 .
drwx------ 6 tester tester 4096 Jul 23 18:26 ..
-rw------- 1 tester tester  817 Jul 23 18:25 2017-04-01 - Professional Motorsport World.opf
```

**Comment by philborman** [comment]
We used to remove the directory tree, but that caused issues if the user had other stuff in the directory, so now we delete files individually. Just added opf to the delete list.

**Comment by sscraggles** [comment]
Just applied the latest update,but fails to restart.


```
root@macmini:/home/htpc# journalctl -xe
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit lazylibrarian.test.service has failed.
-- 
-- The result is failed.
Jul 23 21:51:42 macmini systemd[1]: lazylibrarian.test.service: Unit entered failed state.
Jul 23 21:51:42 macmini systemd[1]: lazylibrarian.test.service: Failed with result 'exit-code'.
Jul 23 21:55:27 macmini systemd[1]: Starting LSB: starts instance of LazyLibrarian...
-- Subject: Unit lazylibrarian.test.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit lazylibrarian.test.service has begun starting up.
Jul 23 21:55:29 macmini lazylibrarian.test[10970]: Starting LazyLibrarian.test:Traceback (most recent call last):
Jul 23 21:55:29 macmini lazylibrarian.test[10970]:   File "LazyLibrarian.py", line 15, in <module>
Jul 23 21:55:29 macmini lazylibrarian.test[10970]:     from lazylibrarian import webStart, logger, versioncheck, dbupgrade
Jul 23 21:55:29 macmini lazylibrarian.test[10970]:   File "/opt/LazyLibrarian.test/lazylibrarian/webStart.py", line 22, in <module>
Jul 23 21:55:29 macmini lazylibrarian.test[10970]:     from lazylibrarian.webServe import WebInterface
Jul 23 21:55:29 macmini lazylibrarian.test[10970]:   File "/opt/LazyLibrarian.test/lazylibrarian/webServe.py", line 1730
Jul 23 21:55:29 macmini lazylibrarian.test[10970]:     for extn in ['.opf', '.jpg']
Jul 23 21:55:29 macmini lazylibrarian.test[10970]:                                ^
Jul 23 21:55:29 macmini lazylibrarian.test[10970]: SyntaxError: invalid syntax
Jul 23 21:55:29 macmini lazylibrarian.test[10970]:  failed!
Jul 23 21:55:29 macmini systemd[1]: lazylibrarian.test.service: Control process exited, code=exited status=1
Jul 23 21:55:29 macmini systemd[1]: Failed to start LSB: starts instance of LazyLibrarian.
```

**Comment by sscraggles** [comment]
I've worked around the startup bug for the time being.  I'm running a sandbox install, cleaned down for the test for reproducability.  Complete log file attached, also worth looking at the mykey entries in the log, where keys aren't getting redacted.
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1168414/debug.zip)

**Comment by philborman** [comment]
ok, thanks will take a look tomorrow. The startup bug was a missing colon on the end of the line. Was fixed here, but didn't get included in the last push. I've just added extra log line stripping options to catch the mykey ones missed in your logfile.

**Comment by sscraggles** [comment]
Updated to 85013f82f88d9b978ac746e3f92da1d3aa292c5e and normal service resumed
