### ISSUE TITLE
Req: allow configuration of calibredb

### ISSUE THREAD

**Issue by sscraggles** [DobyTang/LazyLibrarian#973]
I've had been leaving my calibre server running recently, but this is causing Lazylibrarian to fail the calibre import.  

`07-Aug-2017 14:09:41 - ERROR   :: POSTPROCESS : Postprocessing for The Urgency of Change - Jiddu Krishnamurti has failed: calibredb import failed: Another calibre program such as calibre-server or the main calibre program is running. Having multiple programs that can make changes to a calibre library running at the same time is a bad idea. calibredb can connect directly to a running calibre content server, to make changes through it, instead. See the documentation of the --with-library option for details.`

I tried to work around this as the calibredb error message says by adding the URL switch to the command setting in the Lazylibrarian config, but get the following error.

```
07-Aug-2017 16:23:52 - DEBUG   :: POSTPROCESS : [u'/usr/bin/calibredb --with-library=http://my.home:9000/#eBooks ', 'add', '-1', u'--with-library=/media/Tosh3/eBooks', u"/home/htpc/Downloads/LazyLibrarian/The Urgency of Change - Jiddu Krishnamurti"]
07-Aug-2017 16:23:52 - ERROR   :: POSTPROCESS : Postprocessing for The Urgency of Change -  Jiddu Krishnamurti has failed: calibredb failed, No such file or directory
```

Is it feasible to have an override to this?  Whether though the interface or directly into the config file?

To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
f2de3c16aa2b4417a4a6097868f301ff64a3ee92
### Operating system used (windows, mac, linux, NAS type)
linux

**Comment by philborman** [comment]
I have never managed to get the --with-library=http://my.home:9000/#eBooks ' parameter style working here, only --with-library=file, which seems to work ok. Not sure why it's not working for you, or why the --with-library=url is not working for me. If I could get that working it would be fine.  Any suggestions where I might be going wrong?

I have a calibre content server on http://localhost:9000
if I point my browser at  http://localhost:9000  I get the calibre web interface and can access my books

You should be able to get a list of library IDs with 
calibredb list --with-library="http://localhost:9000/#-"
but I just get
id title authors
(as if it's trying to list the library contents but can't find any, not listing the library ids)

calibredb list --with-library="http://localhost:9000/#Calibre Library"
id title authors
(same)

calibredb list --with-library="/home/phil/Calibre Library"
lists all the books

**Comment by sscraggles** [comment]
Curious, it works for me..

$ /usr/bin/calibredb list --with-library="http://my.home:9000/#-" 
eBooks
Travel Guides
temp

Running calibre 3.6.0

**Comment by philborman** [comment]
I'm currently on 3.4, but my content server is on a raspberry pi running calibre 2.5
Maybe 2.5 doesn't support it and I need to upgrade, but there isn't a calibre3 version for the raspberry pi yet. Debian released one recently for Buster, but it's not backported to Jessie which is what the raspberry pi os is based on.

**Comment by sscraggles** [comment]
Yes, I switched to the install off the [calibre homepage](https://calibre-ebook.com/download_linux),  where they say..
"Please do not use your distribution provided calibre package, as those are often buggy/outdated. Instead use the Binary install described below."

> sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"

It installs nice and cleanly into its own directory in /opt and is more readily update-able than the os packaged versions.

**Comment by philborman** [comment]
Well, just tried to install the Buster version on Jessie, and got the usual dependency hell.
I will have to wait for an official port, or someone else getting fed up and backporting it.

If you want to edit your postprocessor to use --with-library=http://my.home:9000/#eBooks
and don't mind a little editing as a test, there are only a few places in postprocessor.py to edit.

First copy your postprocessor.py to postprocessor.old  (so you can put it back later)

Line 947 says dest_dir = lazylibrarian.DIRECTORY('eBook')
Add a new line below this saying dest_url = 'http://my.home:9000/#eBooks'
The new line needs to be directly under the old one so the word dest_  lines up with the one above. 
Use spaces, not tab to line up.

Lines 969,1001,1017,1031,1045  all '--with-library' and on the next line say dest_dir
Change dest_dir to dest_url

Save the file, restart lazylibrarian, and it should talk to the server url 
If it works, copy your old postprocessor back to postprocessor.py and I will push a proper configurable fix.

**Comment by philborman** [comment]
Yes, the calibre installer is what I use on my laptop (but haven't upgraded since 3.4)
Their installer doesn't run on arm processors though, which is what the pi uses.

**Comment by sscraggles** [comment]
I've tried as you suggested.  Initially had a problem with Calibre reporting 403 auth failure, despite not being configured for authentication and to allow local unauth access.  Trying to import a new book.

```
07-Aug-2017 19:47:33 - DEBUG   :: POSTPROCESS : Importing Urgency of Change - Jiddu Krishnamurti into calibre library
07-Aug-2017 19:47:33 - DEBUG   :: POSTPROCESS : [u'/usr/bin/calibredb', 'add', '-1', '--with-library=http://my.home:9000/#eBooks', u"/home/htpc/Downloads/LazyLibrarian/Urgency of Change - Jiddu Krishnamurti"]
07-Aug-2017 19:47:35 - DEBUG   :: POSTPROCESS : [u'/usr/bin/calibredb', 'add', '-1', '--with-library=http://my.home:9000/#eBooks', u"/home/htpc/Downloads/LazyLibrarian/Urgency of Change - Jiddu Krishnamurti"]
07-Aug-2017 19:47:35 - ERROR   :: POSTPROCESS : Postprocessing forUrgency of Change - Jiddu Krishnamurti has failed: calibredb import failed: The username/password combination is incorrect
```

`10.10.0.123 port-53764 - 07/Aug/2017:20:20:45 +0100 "POST /cdb/cmd/add/0?library_id=eBooks HTTP/1.1" 403 190`

tried to add username password in the form http://username:password@my.home:9000/#eBooks but that didn't work, looks like it needs the extra command switches.

Figured auth problem is due to not running calibre off localhost, so reconfigured that temporarily and set to http://localhost:9000/#eBooks and it _successfully_ imported a new book and added it to Calibre.
Delete doesn't work to remove from Calibre, of course, but sucess! :+1:

**Comment by philborman** [comment]
ok that's great. Thanks for your help.
Will add a config item and push a new version tomorrow.
I'm probably going to go with defaulting to file unless the new config entry is set.

**Comment by philborman** [comment]
New version should use http://calibre_server:port if entered in config, or fall back to using directory containing calibre.db

**Comment by sscraggles** [comment]
Seems to be working, at least partially.  I can add books, but deleting doesn't work.
I tried via the command line and it requires --username= & --password=

Out of interest, would it fall back to command if the server isn't running, or is that a stretch too far.

**Comment by philborman** [comment]
Deleting is working here using - - with-library=file. Doesn't need user or password. Maybe the - - with-file=url is different. What does debug log show for the delete? (we print the output from calibredb)

I might try cross compiling calibre 3.6 for the pi, but at the moment there is only v2.75 available in the debian repo for arm processors. 

As for falling back to command if no server, calibredb will presumably report an error if no server is running, though I don't know what as I can't test it. If we knew what the error message was we could probably try a second command using the filename instead.

**Comment by sscraggles** [comment]
Scratch my previous comment.   It all works for localhost and fails for non loopback address.
I had my calibre server bound to an external address only, changed it to all interfaces and pointed it Lazylibrarian to the loopback and it works.


In detail....


 If the URL is set to http://localhost:9000 it was successfully removed from Calibre....
```
09-Aug-2017 03:30:22 - INFO    :: WEBSERVER : eBook Luciano's Luck deleted from disc
09-Aug-2017 03:30:23 - DEBUG   :: WEBSERVER : [u'/usr/bin/calibredb', 'remove', u'8', '--with-library', u'http://localhost:9000']
09-Aug-2017 03:30:25 - DEBUG   :: WEBSERVER : No response from /usr/bin/calibredb
09-Aug-2017 03:30:25 - DEBUG   :: WEBSERVER : Status set to Ignored for "Luciano's Luck"

```

using a non loopback hostname doesn't remove it from Calibre, but does from Lazylibrarian and filesystem ..
```
09-Aug-2017 02:52:41 - INFO    :: WEBSERVER : eBook Luciano's Luck deleted from disc
09-Aug-2017 02:52:41 - DEBUG   :: WEBSERVER : [u'/usr/bin/calibredb', 'remove', u'6', '--with-library', u'http://my.home:9000']
09-Aug-2017 02:52:42 - DEBUG   :: WEBSERVER : rmtree failed on /home/scraggles/booktest/Jack Higgins/Luciano's Luck (6)/Luciano's Luck - Jack Higgins.epub, Command '[u'/usr/bin/calibredb', 'remove', u'6', '--with-library', u'http://my.home:9000']' returned non-zero exit status 1
09-Aug-2017 02:52:42 - DEBUG   :: WEBSERVER : Status set to Ignored for "Luciano's Luck"
```

Equivilent via the commandline
```
$ calibredb --with-library=http://macmini.home:9000#booktest remove 6
The username/password combination is incorrect
$
```
```
$ calibredb --with-library=http://localhost:9000#booktest remove 6
$
```





Also Successfully download/import, with localhost configured

```
09-Aug-2017 03:24:16 - DEBUG   :: POSTPROCESS : Checking 1 file in /home/scraggles/Downloads/LazyLibrarian
09-Aug-2017 03:24:16 - DEBUG   :: POSTPROCESS : Found 1 file marked "Snatched"
09-Aug-2017 03:24:16 - DEBUG   :: POSTPROCESS : Jack Higgins - Lucianos Luck LL.(564505) was sent to SABNZBD
09-Aug-2017 03:24:16 - INFO    :: POSTPROCESS : Looking for eBook Jack Higgins - Lucianos Luck LL.(564505) in /home/scraggles/Downloads/LazyLibrarian
09-Aug-2017 03:24:16 - DEBUG   :: POSTPROCESS : Checking extn on Jack Higgins - Lucianos Luck LL.(564505)
09-Aug-2017 03:24:16 - DEBUG   :: POSTPROCESS : 100% match Jack Higgins - Lucianos Luck : Jack Higgins - Lucianos Luck
09-Aug-2017 03:24:16 - DEBUG   :: POSTPROCESS : processDir <type 'unicode'> u'/home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505)'
09-Aug-2017 03:24:16 - DEBUG   :: POSTPROCESS : Found folder (100%) [/home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505)] for eBook Jack Higgins - Lucianos Luck
09-Aug-2017 03:24:16 - DEBUG   :: POSTPROCESS : Found match (100%): /home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505) for eBook Jack Higgins - Lucianos Luck LL.(564505)
09-Aug-2017 03:24:16 - DEBUG   :: POSTPROCESS : Processing eBook 564505
09-Aug-2017 03:24:16 - DEBUG   :: POSTPROCESS : Importing Luciano's Luck - Jack Higgins into calibre library
09-Aug-2017 03:24:16 - DEBUG   :: POSTPROCESS : [u'/usr/bin/calibredb', 'add', '-1', '--with-library', u'http://localhost:9000', u'/home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505)']
09-Aug-2017 03:24:21 - DEBUG   :: POSTPROCESS : /usr/bin/calibredb reports: Added book ids: 8

09-Aug-2017 03:24:21 - DEBUG   :: POSTPROCESS : Calibre ID: 8
09-Aug-2017 03:24:21 - DEBUG   :: POSTPROCESS : Saved metadata to: /home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505)/Luciano's Luck - Jack Higgins.opf
09-Aug-2017 03:24:21 - DEBUG   :: POSTPROCESS : [u'/usr/bin/calibredb', 'set_metadata', '--with-library', u'http://localhost:9000', '8', u"/home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505)/Luciano's Luck - Jack Higgins.opf"]
09-Aug-2017 03:24:23 - DEBUG   :: POSTPROCESS : /usr/bin/calibredb set opf reports: Title               : Luciano's Luck
Title sort          : Luciano's Luck
Author(s)           : Jack Higgins
Publisher           : Stein & Day Pub
Languages           : eng
Rating              : 3
Timestamp           : 2017-08-09T02:24:19.548412+00:00
Published           : 1981-06-01T00:00:00+00:00
Identifiers         : goodreads:564505
Comments            : <h3>From Library Journal</h3><p>Dove Audio goes to the head of the pack with this exciting, unabridged rendition of Higgins's (Sheba, Audio Reviews, LJ 2/15/95) story of an Allied plan to release Lucky Luciano from prison. Luciano is slated to join a team that includes the granddaughter of Luciano's Mafia counterpart in Sicily and a crack Special Services operative. Their objective: to persuade the Don to rally the people of Sicily to aid the Allies in their effort to run the Axis forces off the island, paving the way for the Allied invasion of Italy. The action builds to a riveting climax and concomitant bloody conclusion. British actor and former Avenger Patrick Macnee is required to juggle Sicilian, German, American, and Ukrainian accents and does so superbly. Best of all, this unabridged recording is reasonably priced. Recommended for most public libraries.?Mark Pumphrey, Polk Cty. P.L., Columbus, N.C.<br />Copyright 1997 Reed Business Information, Inc. </p><h3>Review</h3><p>"Jack Higgins is the master." Tom Clancy</p>

09-Aug-2017 03:24:23 - DEBUG   :: POSTPROCESS : Calibre trying directory [/home/scraggles/booktest/Jack Higgins/Luciano's Luck (8)]
09-Aug-2017 03:24:23 - INFO    :: POSTPROCESS : Scanning eBook directory: /home/scraggles/booktest/Jack Higgins/Luciano's Luck (8)
09-Aug-2017 03:24:23 - DEBUG   :: POSTPROCESS : [/home/scraggles/booktest/Jack Higgins/Luciano's Luck (8)] Now scanning subdirectory 
09-Aug-2017 03:24:23 - DEBUG   :: POSTPROCESS : book meta [9780812828276] [en] [Jack Higgins] [Luciano's Luck] [epub]
09-Aug-2017 03:24:23 - DEBUG   :: POSTPROCESS : file meta [9780812828276] [eng] [Jack Higgins] [Luciano's Luck] [564505]
09-Aug-2017 03:24:23 - DEBUG   :: POSTPROCESS : Found Language [eng] ISBN [9780812828276]
09-Aug-2017 03:24:23 - DEBUG   :: POSTPROCESS : Already cached Lang [eng] ISBN [081]
09-Aug-2017 03:24:23 - DEBUG   :: POSTPROCESS : Searching database for [Lucianos Luck] by [Jack Higgins]
09-Aug-2017 03:24:23 - DEBUG   :: POSTPROCESS : Searching 119 books by [Jack Higgins] in database for [Lucianos Luck]

<snipped>

09-Aug-2017 03:24:23 - DEBUG   :: POSTPROCESS : PartialRatio 46 [lucianos luck][jack higgins collection - toll for the brave & to catch a king]
09-Aug-2017 03:24:23 - DEBUG   :: POSTPROCESS : Fuzz match partial [92] [Lucianos Luck] [Luciano's Luck]
09-Aug-2017 03:24:24 - DEBUG   :: POSTPROCESS : Librarysync link to preferred type epub: /home/scraggles/booktest/Jack Higgins/Luciano's Luck (8)/Luciano's Luck - Jack Higgins.epub
09-Aug-2017 03:24:24 - WARNING :: POSTPROCESS : Updating book location for Jack Higgins Lucianos Luck from /home/scraggles/booktest/Jack Higgins/Luciano's Luck (7)/Luciano's Luck - Jack Higgins.epub to /home/scraggles/booktest/Jack Higgins/Luciano's Luck (8)/Luciano's Luck - Jack Higgins.epub
09-Aug-2017 03:24:24 - DEBUG   :: POSTPROCESS : Jack Higgins Lucianos Luck matched Snatched BookID 564505, [Jack Higgins][Luciano's Luck]
09-Aug-2017 03:24:24 - INFO    :: POSTPROCESS : 1/1 new/modified eBooks found and added to the database
09-Aug-2017 03:24:24 - INFO    :: POSTPROCESS : 3 files processed
09-Aug-2017 03:24:24 - DEBUG   :: POSTPROCESS : Updating bookcounts for 1 author
09-Aug-2017 03:24:24 - INFO    :: POSTPROCESS : Library scan complete
09-Aug-2017 03:24:24 - DEBUG   :: POSTPROCESS : Processed nzb: Luciano's Luck - Jack Higgins, https://api.nzbgeek.info/api?t=get&id=mykeu&apikey=mykey
09-Aug-2017 03:24:24 - DEBUG   :: POSTPROCESS : Cover /home/scraggles/booktest/Jack Higgins/Luciano's Luck (8)/cover.jpg already exists
09-Aug-2017 03:24:24 - DEBUG   :: POSTPROCESS : Saved metadata to: /home/scraggles/booktest/Jack Higgins/Luciano's Luck (8)/Luciano's Luck - Jack Higgins.opf
09-Aug-2017 03:24:24 - DEBUG   :: POSTPROCESS : Removing Jack Higgins - Lucianos Luck LL.(564505) from sabnzbd
09-Aug-2017 03:24:24 - DEBUG   :: POSTPROCESS : Request url for <a href="http://macmini.home:8080/api?ma_password=easy&apikey=mykey&name=delete&value=SABnzbd_nzo_h81XiI&mode=queue&output=json&ma_username=htpc">SABnzbd</a>
09-Aug-2017 03:24:24 - DEBUG   :: POSTPROCESS : Result text from SAB: {u'status': False, u'nzo_ids': []}
09-Aug-2017 03:24:24 - DEBUG   :: POSTPROCESS : Request url for <a href="http://macmini.home:8080/api?ma_password=easy&apikey=mykey&name=delete&value=SABnzbd_nzo_h81XiI&mode=history&output=json&ma_username=htpc">SABnzbd</a>
09-Aug-2017 03:24:24 - DEBUG   :: POSTPROCESS : Result text from SAB: {u'status': True}
09-Aug-2017 03:24:24 - DEBUG   :: POSTPROCESS : Deleted Jack Higgins - Lucianos Luck LL.(564505), nzb from sabnzbd
09-Aug-2017 03:24:24 - INFO    :: POSTPROCESS : Successfully processed: Luciano's Luck - Jack Higgins
09-Aug-2017 03:24:24 - DEBUG   :: POSTPROCESS : Scanning 0 entries in /home/scraggles/Downloads/LazyLibrarian for LL.(num)
09-Aug-2017 03:24:24 - INFO    :: POSTPROCESS : 1 book/mag processed.
09-Aug-2017 03:24:24 - INFO    :: POSTPROCESS : Nothing marked as snatched. Stopping postprocessor.
09-Aug-2017 03:24:24 - DEBUG   :: POSTPROCESS : Stop processDir job

```

and failed to add to Calibre and Lazylibrarian with non loopback address... 
```
09-Aug-2017 03:41:42 - DEBUG   :: POSTPROCESS : Checking 1 file in /home/scraggles/Downloads/LazyLibrarian
09-Aug-2017 03:41:42 - DEBUG   :: POSTPROCESS : Found 1 file marked "Snatched"
09-Aug-2017 03:41:42 - DEBUG   :: POSTPROCESS : Jack Higgins - Lucianos Luck LL.(564505) was sent to SABNZBD
09-Aug-2017 03:41:42 - INFO    :: POSTPROCESS : Looking for eBook Jack Higgins - Lucianos Luck LL.(564505) in /home/scraggles/Downloads/LazyLibrarian
09-Aug-2017 03:41:42 - DEBUG   :: POSTPROCESS : Checking extn on Jack Higgins - Lucianos Luck LL.(564505)
09-Aug-2017 03:41:42 - DEBUG   :: POSTPROCESS : 100% match Jack Higgins - Lucianos Luck : Jack Higgins - Lucianos Luck
09-Aug-2017 03:41:42 - DEBUG   :: POSTPROCESS : processDir <type 'unicode'> u'/home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505)'
09-Aug-2017 03:41:42 - DEBUG   :: POSTPROCESS : Found folder (100%) [/home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505)] for eBook Jack Higgins - Lucianos Luck
09-Aug-2017 03:41:42 - DEBUG   :: POSTPROCESS : Found match (100%): /home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505) for eBook Jack Higgins - Lucianos Luck LL.(564505)
09-Aug-2017 03:41:42 - DEBUG   :: POSTPROCESS : Processing eBook 564505
09-Aug-2017 03:41:42 - DEBUG   :: POSTPROCESS : Importing Luciano's Luck - Jack Higgins into calibre library
09-Aug-2017 03:41:42 - DEBUG   :: POSTPROCESS : [u'/usr/bin/calibredb', 'add', '-1', '--with-library', u'http://macmini.home:9000', u'/home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505)']
09-Aug-2017 03:41:43 - DEBUG   :: POSTPROCESS : []
09-Aug-2017 03:41:43 - ERROR   :: POSTPROCESS : Postprocessing for Luciano's Luck - Jack Higgins has failed: calibredb import failed: The username/password combination is incorrect

09-Aug-2017 03:41:44 - WARNING :: POSTPROCESS : Residual files remain in /home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505).fail
09-Aug-2017 03:41:44 - DEBUG   :: POSTPROCESS : Scanning 1 entries in /home/scraggles/Downloads/LazyLibrarian for LL.(num)
09-Aug-2017 03:41:44 - DEBUG   :: POSTPROCESS : Skipping extn Jack Higgins - Lucianos Luck LL.(564505).fail
09-Aug-2017 03:41:44 - INFO    :: POSTPROCESS : 0 books/mags processed.
09-Aug-2017 03:41:44 - INFO    :: POSTPROCESS : Nothing marked as snatched. Stopping postprocessor.
09-Aug-2017 03:41:44 - DEBUG   :: POSTPROCESS : Stop processDir job

```

**Comment by sscraggles** [comment]
Heres what happens with Calibre server turned off...
```
09-Aug-2017 03:48:13 - DEBUG   :: POSTPROCESS : Checking 1 file in /home/scraggles/Downloads/LazyLibrarian
09-Aug-2017 03:48:13 - DEBUG   :: POSTPROCESS : Found 1 file marked "Snatched"
09-Aug-2017 03:48:13 - DEBUG   :: POSTPROCESS : Jack Higgins - Lucianos Luck LL.(564505) was sent to SABNZBD
09-Aug-2017 03:48:13 - INFO    :: POSTPROCESS : Looking for eBook Jack Higgins - Lucianos Luck LL.(564505) in /home/scraggles/Downloads/LazyLibrarian
09-Aug-2017 03:48:13 - DEBUG   :: POSTPROCESS : Checking extn on Jack Higgins - Lucianos Luck LL.(564505)
09-Aug-2017 03:48:13 - DEBUG   :: POSTPROCESS : 100% match Jack Higgins - Lucianos Luck : Jack Higgins - Lucianos Luck
09-Aug-2017 03:48:13 - DEBUG   :: POSTPROCESS : processDir <type 'unicode'> u'/home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505)'
09-Aug-2017 03:48:13 - DEBUG   :: POSTPROCESS : Found folder (100%) [/home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505)] for eBook Jack Higgins - Lucianos Luck
09-Aug-2017 03:48:13 - DEBUG   :: POSTPROCESS : Found match (100%): /home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505) for eBook Jack Higgins - Lucianos Luck LL.(564505)
09-Aug-2017 03:48:13 - DEBUG   :: POSTPROCESS : Processing eBook 564505
09-Aug-2017 03:48:13 - DEBUG   :: POSTPROCESS : Importing Luciano's Luck - Jack Higgins into calibre library
09-Aug-2017 03:48:13 - DEBUG   :: POSTPROCESS : [u'/usr/bin/calibredb', 'add', '-1', '--with-library', u'http://localhost:9000', u'/home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505)']
09-Aug-2017 03:48:15 - DEBUG   :: POSTPROCESS : []
09-Aug-2017 03:48:15 - ERROR   :: POSTPROCESS : Postprocessing for Luciano's Luck - Jack Higgins has failed: calibredb import failed: Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/db/cli/main.py", line 251, in main
  File "site-packages/calibre/db/cli/main.py", line 55, in run_cmd
  File "site-packages/calibre/db/cli/cmd_add.py", line 374, in main
  File "site-packages/calibre/db/cli/cmd_add.py", line 178, in do_add
  File "site-packages/calibre/db/adding.py", line 173, in import_book_directory
  File "site-packages/calibre/db/cli/cmd_add.py", line 79, in add_books
  File "site-packages/calibre/db/cli/main.py", line 189, in run
  File "site-packages/calibre/db/cli/main.py", line 209, in remote_run
  File "site-packages/mechanize/_mechanize.py", line 239, in open_novisit
  File "site-packages/mechanize/_mechanize.py", line 284, in _mech_open
  File "site-packages/mechanize/_opener.py", line 195, in open
  File "site-packages/mechanize/_urllib2_fork.py", line 352, in _open
  File "site-packages/mechanize/_urllib2_fork.py", line 340, in _call_chain
  File "site-packages/mechanize/_urllib2_fork.py", line 1188, in http_open
  File "site-packages/mechanize/_urllib2_fork.py", line 1160, in do_open
URLError: <urlopen error [Errno 111] Connection refused>

09-Aug-2017 03:48:15 - WARNING :: POSTPROCESS : Residual files remain in /home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505).fail
09-Aug-2017 03:48:15 - DEBUG   :: POSTPROCESS : Scanning 1 entries in /home/scraggles/Downloads/LazyLibrarian for LL.(num)
09-Aug-2017 03:48:15 - DEBUG   :: POSTPROCESS : Skipping extn Jack Higgins - Lucianos Luck LL.(564505).fail
09-Aug-2017 03:48:15 - INFO    :: POSTPROCESS : 0 books/mags processed.
09-Aug-2017 03:48:15 - INFO    :: POSTPROCESS : Nothing marked as snatched. Stopping postprocessor.
09-Aug-2017 03:48:15 - DEBUG   :: POSTPROCESS : Stop processDir job
```

**Comment by philborman** [comment]
ok, thanks for that. I will look for the "Errno 111" message from calibredb and retry with file.

**Comment by sscraggles** [comment]
Retried calibre server off with todays 9a9e03e14a625dcdb5bf2afc8bc152ea270bab71

Still fails to add...

```
13-Aug-2017 00:28:23 - DEBUG   :: POSTPROCESS : Alison Weir - Lancaster And York LL.(17429716) was sent to SABNZBD
13-Aug-2017 00:28:23 - INFO    :: POSTPROCESS : Looking for eBook Alison Weir - Lancaster And York LL.(17429716) in /home/htpc/Downloads/LazyLibrarian
13-Aug-2017 00:28:23 - DEBUG   :: POSTPROCESS : Checking extn on Alison Weir - Lancaster And York LL.(17429716)
13-Aug-2017 00:28:23 - DEBUG   :: POSTPROCESS : 100% match Alison Weir - Lancaster And York : Alison Weir - Lancaster And York
13-Aug-2017 00:28:23 - DEBUG   :: POSTPROCESS : processDir <type 'unicode'> u'/home/htpc/Downloads/LazyLibrarian/Alison Weir - Lancaster And York LL.(17429716)'
13-Aug-2017 00:28:23 - DEBUG   :: POSTPROCESS : Found folder (100%) [/home/htpc/Downloads/LazyLibrarian/Alison Weir - Lancaster And York LL.(17429716)] for eBook Alison Weir - Lancaster And York
13-Aug-2017 00:28:23 - DEBUG   :: POSTPROCESS : Found match (100%): /home/htpc/Downloads/LazyLibrarian/Alison Weir - Lancaster And York LL.(17429716) for eBook Alison Weir - Lancaster And York LL.(17429716)
13-Aug-2017 00:28:23 - DEBUG   :: POSTPROCESS : Processing eBook 17429716
13-Aug-2017 00:28:23 - DEBUG   :: POSTPROCESS : Importing Lancaster And York - Alison Weir into calibre library
13-Aug-2017 00:28:23 - DEBUG   :: POSTPROCESS : [u'/usr/bin/calibredb', 'add', '-1', '--with-library', u'http://localhost:9000', u'/home/htpc/Downloads/LazyLibrarian/Alison Weir - Lancaster And York LL.(17429716)']
13-Aug-2017 00:28:29 - DEBUG   :: POSTPROCESS : []
13-Aug-2017 00:28:29 - ERROR   :: POSTPROCESS : Postprocessing for Lancaster And York - Alison Weir has failed: calibredb import failed: Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/db/cli/main.py", line 251, in main
  File "site-packages/calibre/db/cli/main.py", line 55, in run_cmd
  File "site-packages/calibre/db/cli/cmd_add.py", line 374, in main
  File "site-packages/calibre/db/cli/cmd_add.py", line 178, in do_add
  File "site-packages/calibre/db/adding.py", line 173, in import_book_directory
  File "site-packages/calibre/db/cli/cmd_add.py", line 79, in add_books
  File "site-packages/calibre/db/cli/main.py", line 189, in run
  File "site-packages/calibre/db/cli/main.py", line 209, in remote_run
  File "site-packages/mechanize/_mechanize.py", line 239, in open_novisit
  File "site-packages/mechanize/_mechanize.py", line 284, in _mech_open
  File "site-packages/mechanize/_opener.py", line 195, in open
  File "site-packages/mechanize/_urllib2_fork.py", line 352, in _open
  File "site-packages/mechanize/_urllib2_fork.py", line 340, in _call_chain
  File "site-packages/mechanize/_urllib2_fork.py", line 1188, in http_open
  File "site-packages/mechanize/_urllib2_fork.py", line 1160, in do_open
URLError: <urlopen error [Errno 111] Connection refused>

13-Aug-2017 00:28:29 - WARNING :: POSTPROCESS : Residual files remain in /home/htpc/Downloads/LazyLibrarian/Alison Weir - Lancaster And York LL.(17429716).fail
13-Aug-2017 00:28:29 - DEBUG   :: POSTPROCESS : Scanning 1 entries in /home/htpc/Downloads/LazyLibrarian for LL.(num)
13-Aug-2017 00:28:29 - DEBUG   :: POSTPROCESS : Skipping extn Alison Weir - Lancaster And York LL.(17429716).fail
13-Aug-2017 00:28:29 - INFO    :: POSTPROCESS : 0 books/mags processed.
13-Aug-2017 00:28:29 - DEBUG   :: POSTPROCESS : Stop processDir job
13-Aug-2017 00:28:29 - DEBUG   :: POSTPROCESS : Restart processDir job in 10 minutes
```

**Comment by philborman** [comment]
Calibre doesn't send it's message back to python as an error, that seems to be why we are missing it. 
We are looking in stderr, and the message appears in stdout. Should be fixed now. Had to bypass the nice python function used to call subprocess, and do it myself using pipes (found a nice example on the internet)

Also added user/password fields if you're talking to the calibre content server, as without auth you only have read access, not the write access needed to add/remove books or change metadata.  

You need to start the calibre content server with calibre-server --port=whatever --enable-auth 
 or if using calibre itself as the content server you need to enable auth in the calibre config (its under preferences / sharing over the net) and set up at least one user account.

calibre content server entry in lazylibrarian  should be http://host:port/#libraryname  or you can skip the libraryname part if using the default library.

**Comment by sscraggles** [comment]
Great, username/password is a useful addition though I've been running okay without authentication.

Starting calibre-server with --enable-local-write allows write access without username/password enabled - when using http://**localhost**:9000 .
This works so long as calibre-server is started with --listen-on=:: (or --listen-on=0.0.0.0 if no ipv6 loopback is configured).

Seems to be working okay if I just leave username & password blank, though I am seeing an error in the debug log.  maybe nothing.
```
13-Aug-2017 22:24:50 - INFO    :: WEBSERVER : eBook Lancaster And York deleted from disc
13-Aug-2017 22:24:50 - DEBUG   :: WEBSERVER : [u'/usr/bin/calibredb', 'remove', u'5317', '--with-library', u'http://localhost:9000/#eBooks']
13-Aug-2017 22:24:53 - DEBUG   :: WEBSERVER : rmtree failed on /media/Tosh3/eBooks/Alison Weir/Lancaster And York (5317)/Lancaster And York - Alison Weir.epub, 'tuple' object has no attribute 'decode'
13-Aug-2017 22:24:53 - DEBUG   :: WEBSERVER : Status set to Ignored for "Lancaster And York"
```

Also tested with calibre-server off and it now sucessfully falls back to the directory method.
```
13-Aug-2017 22:29:36 - INFO    :: WEBSERVER : eBook Lancaster And York deleted from disc
13-Aug-2017 22:29:36 - DEBUG   :: WEBSERVER : [u'/usr/bin/calibredb', 'remove', u'5318', '--with-library', u'http://localhost:9000/#eBooks']
13-Aug-2017 22:29:37 - DEBUG   :: WEBSERVER : calibredb returned 1: Connection refused
13-Aug-2017 22:29:37 - DEBUG   :: WEBSERVER : [u'/usr/bin/calibredb', 'remove', u'5318', '--with-library', u'/media/Tosh3/eBooks']
13-Aug-2017 22:29:39 - DEBUG   :: WEBSERVER : rmtree failed on /media/Tosh3/eBooks/Alison Weir/Lancaster And York (5318)/Lancaster And York - Alison Weir.epub, 'tuple' object has no attribute 'decode'
13-Aug-2017 22:29:39 - DEBUG   :: WEBSERVER : Status set to Ignored for "Lancaster And York"
```

**Comment by philborman** [comment]
no auth only works if the calibre server is on the same machine as the calibredb instance.
I don't think it even works over local network, ie 127.0.0.x  I will mention   --enable-local-write  in the wiki though, there are loads of different ways to talk to calibre, each with their limitations.

The rmtree failed message is a bug, will look into it tomorrow.

**Comment by sscraggles** [comment]
Thanks, not sure I was clear.  I was attempting to illustrate the importance of how calibre-server is started.

For example, if calibre-server is started with a network only address (non loopback/localhost), eg --listen-on=192.168.0.10 then authentication is needed to make changes, whether from a local machine or not.  The only address which will work is http://192.168.0.10:9000

If calibre-server is started with --listen-on=:: or --listen-on=0.0.0.0 it can be accessed via http://localhost:9000 and http://192.168.0.10:9000 as well as any other IP addresses configured on that machine.   That way and for Lazylibrarian purposes, localhost can be accessed without authentication in conjunction with the --enable-local-write switch.

**Comment by philborman** [comment]
Thanks, I have added that to the wiki
