### ISSUE TITLE
Unhandled exception .. formatter.py

### ISSUE THREAD

**Issue by billbo99** [DobyTang/LazyLibrarian#992]
Was pulling down the list of books by "Morgan Rice" and I got an "Unhandled exception" for this entry in goodreads.

I did some debugging and it could not extract the title
```
<id type="integer">23284780</id>
<isbn>1322142114</isbn>
<isbn13>9781322142111</isbn13>
<text_reviews_count type="integer">0</text_reviews_count>
<title/>
<title_without_series/>
```

So when it came to decode the title it broke out with a NoneType error.

``` python
Unhandled exception in GR.get_author_books: Traceback (most recent call last):
  File "/home/xxx/PycharmProjects/LazyLibrarian/lazylibrarian/gr.py", line 510, in get_author_books
    bookname = unaccented(bookname)
  File "/home/xxx/PycharmProjects/LazyLibrarian/lazylibrarian/formatter.py", line 381, in unaccented
    return unaccented_str(str_or_unicode).decode(lazylibrarian.SYS_ENCODING)
  File "/home/xxx/PycharmProjects/LazyLibrarian/lazylibrarian/formatter.py", line 389, in unaccented_str
    nfkd_form = unicodedata.normalize('NFKD', str_or_unicode.decode(lazylibrarian.SYS_ENCODING, 'replace'))
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by philborman** [comment]
Ok thanks, easy to fix, will push a new version tomorrow.
